use std::io::{BufRead, BufReader};
use std::os::windows::process::CommandExt;
use std::path::PathBuf;
use std::process::{Command, Stdio};
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::{Mutex, OnceLock};
use std::time::{Duration, SystemTime, UNIX_EPOCH};

use serde::{Deserialize, Serialize};
use tauri::menu::{Menu, MenuItem};
use tauri::tray::{MouseButton, MouseButtonState, TrayIconBuilder, TrayIconEvent};
use tauri::{AppHandle, Emitter, Manager};

/// The npm package that ships the harness.
const PKG_NAME: &str = "@deepseek-ai/dsh";
/// Same package, percent-encoded the way a registry metadata URL expects it.
const PKG_URL_PATH: &str = "@deepseek-ai%2Fdsh";
const DEFAULT_REGISTRY: &str = "https://registry.npmmirror.com";
/// "once a day" — 24h between automatic checks.
const CHECK_INTERVAL_SECS: u64 = 24 * 60 * 60;
/// The port this machine's harness UI is normally served on.
const DEFAULT_HARNESS_PORT: u16 = 3080;
const TRAY_ID: &str = "main-tray";

/// Tray icons are the app logo: colour = running, greyscale = stopped, one set
/// per taskbar theme. Generated by tools/make_icons.py.
const TRAY_OFF_DARK: &[u8] = include_bytes!("../icons-tray/tray-stopped-dark.png");
const TRAY_ON_DARK: &[u8] = include_bytes!("../icons-tray/tray-running-dark.png");
const TRAY_OFF_LIGHT: &[u8] = include_bytes!("../icons-tray/tray-stopped-light.png");
const TRAY_ON_LIGHT: &[u8] = include_bytes!("../icons-tray/tray-running-light.png");
/// How often the tray polls the harness port and the taskbar theme.
const HARNESS_POLL_SECS: u64 = 10;
/// Written by the poller thread, read when refreshing the tray.
static HARNESS_RUNNING: AtomicBool = AtomicBool::new(false);
/// Whether the taskbar is light (SystemUsesLightTheme), also set by the poller.
static TASKBAR_LIGHT: AtomicBool = AtomicBool::new(false);
/// The harness process started from inside the panel. Kept so its pipes stay
/// alive; dropping this handle does NOT kill the child process.
static HARNESS_CHILD: OnceLock<Mutex<Option<std::process::Child>>> = OnceLock::new();
/// The Electron desktop app started from source; same deal.
static DESKTOP_CHILD: OnceLock<Mutex<Option<std::process::Child>>> = OnceLock::new();

fn harness_url(port: u16) -> String {
    format!("http://127.0.0.1:{port}/")
}

// Windows process creation flags.
const CREATE_NO_WINDOW: u32 = 0x0800_0000;
const CREATE_NEW_CONSOLE: u32 = 0x0000_0010;

// ---------------------------------------------------------------------------
// Data shapes handed to the frontend
// ---------------------------------------------------------------------------

#[derive(Serialize, Clone)]
struct LocalInfo {
    ok: bool,
    dsh_version: Option<String>,
    node_dir: Option<String>,
    node_version: Option<String>,
    error: Option<String>,
}

#[derive(Serialize, Clone)]
struct UpdateInfo {
    ok: bool,
    local_version: Option<String>,
    latest_version: Option<String>,
    has_update: bool,
    registry: String,
    checked_at: u64,
    error: Option<String>,
}

#[derive(Serialize, Clone)]
struct ActionResult {
    ok: bool,
    action: String,
    message: String,
    output: String,
}

#[derive(Serialize, Deserialize, Clone, Default)]
struct PersistedState {
    last_check_at: Option<u64>,
    last_latest_version: Option<String>,
    last_local_version: Option<String>,
}

// ---------------------------------------------------------------------------
// Local install discovery
// ---------------------------------------------------------------------------

fn now_secs() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0)
}

/// Strip the `\\?\` prefix `canonicalize` adds on Windows.
fn clean_path(p: PathBuf) -> PathBuf {
    let s = p.to_string_lossy().to_string();
    match s.strip_prefix(r"\\?\") {
        Some(rest) => PathBuf::from(rest),
        None => p,
    }
}

/// Locate the active Node install by finding `dsh.cmd` on PATH.
///
/// npm puts its global shims directly in the Node install root, so the directory
/// holding `dsh.cmd` *is* the Node root for whichever nvm version is active.
/// This tracks `nvm use` automatically — no hardcoded nvm paths.
fn find_node_dir() -> Option<PathBuf> {
    let path = std::env::var_os("PATH")?;
    for dir in std::env::split_paths(&path) {
        if dir.join("dsh.cmd").is_file() {
            return Some(dir);
        }
    }
    None
}

fn read_local() -> LocalInfo {
    let Some(node_dir) = find_node_dir() else {
        return LocalInfo {
            ok: false,
            dsh_version: None,
            node_dir: None,
            node_version: None,
            error: Some(
                "PATH 上找不到 dsh.cmd：dsh 可能没装，或当前 nvm 版本里没有它".to_string(),
            ),
        };
    };

    let pkg = node_dir
        .join("node_modules")
        .join("@deepseek-ai")
        .join("dsh")
        .join("package.json");

    let installed = std::fs::read_to_string(&pkg)
        .ok()
        .and_then(|t| serde_json::from_str::<serde_json::Value>(&t).ok())
        .and_then(|v| {
            v.get("version")
                .and_then(|x| x.as_str())
                .map(|s| s.to_string())
        });

    // Directory name of the resolved junction, e.g. v24.9.0
    let node_version = std::fs::canonicalize(&node_dir)
        .map(clean_path)
        .ok()
        .and_then(|p| p.file_name().map(|n| n.to_string_lossy().to_string()))
        .filter(|n| n.starts_with('v'));

    LocalInfo {
        ok: installed.is_some(),
        error: if installed.is_none() {
            Some(format!("找到 Node 目录，但读不到 {}", pkg.display()))
        } else {
            None
        },
        dsh_version: installed,
        node_dir: Some(node_dir.to_string_lossy().to_string()),
        node_version,
    }
}

/// Respect the user's npm registry (npmmirror on this machine) so the version we
/// report is the one that can actually be installed.
fn read_registry() -> String {
    if let Some(home) = std::env::var_os("USERPROFILE") {
        let npmrc = PathBuf::from(home).join(".npmrc");
        if let Ok(txt) = std::fs::read_to_string(&npmrc) {
            for line in txt.lines() {
                let line = line.trim();
                if let Some(rest) = line.strip_prefix("registry=") {
                    let v = rest.trim().trim_end_matches('/');
                    if !v.is_empty() {
                        return v.to_string();
                    }
                }
            }
        }
    }
    DEFAULT_REGISTRY.to_string()
}

// ---------------------------------------------------------------------------
// Registry check
// ---------------------------------------------------------------------------

async fn fetch_latest(registry: &str) -> Result<String, String> {
    let url = format!("{}/{}", registry.trim_end_matches('/'), PKG_URL_PATH);
    let client = reqwest::Client::builder()
        .timeout(Duration::from_secs(20))
        .user_agent("dsh-panel")
        .build()
        .map_err(|e| format!("创建 HTTP 客户端失败: {e}"))?;

    let resp = client
        .get(&url)
        .send()
        .await
        .map_err(|e| format!("请求 registry 失败: {e}"))?;

    if !resp.status().is_success() {
        return Err(format!("registry 返回 HTTP {}", resp.status()));
    }

    let body: serde_json::Value = resp
        .json()
        .await
        .map_err(|e| format!("解析 registry 响应失败: {e}"))?;

    body.get("dist-tags")
        .and_then(|t| t.get("latest"))
        .and_then(|s| s.as_str())
        .map(|s| s.to_string())
        .ok_or_else(|| "registry 响应里没有 dist-tags.latest".to_string())
}

fn is_newer(latest: &str, current: Option<&str>) -> bool {
    let Some(cur) = current else { return false };
    match (
        semver::Version::parse(latest),
        semver::Version::parse(cur),
    ) {
        (Ok(l), Ok(c)) => l > c,
        _ => latest != cur,
    }
}

async fn run_check(app: &AppHandle) -> UpdateInfo {
    let local = read_local();
    let registry = read_registry();
    let now = now_secs();

    let mut info = UpdateInfo {
        ok: false,
        local_version: local.dsh_version.clone(),
        latest_version: None,
        has_update: false,
        registry: registry.clone(),
        checked_at: now,
        error: None,
    };

    if local.dsh_version.is_none() {
        info.error = local.error.clone();
        return info;
    }

    match fetch_latest(&registry).await {
        Ok(latest) => {
            info.has_update = is_newer(&latest, local.dsh_version.as_deref());
            info.latest_version = Some(latest.clone());
            info.ok = true;
            save_state(
                app,
                &PersistedState {
                    last_check_at: Some(now),
                    last_latest_version: Some(latest),
                    last_local_version: local.dsh_version,
                },
            );
            refresh_tray(app);
        }
        Err(e) => info.error = Some(e),
    }

    info
}

// ---------------------------------------------------------------------------
// Persisted state (drives the "once a day" rule)
// ---------------------------------------------------------------------------

fn state_file(app: &AppHandle) -> Option<PathBuf> {
    let dir = app.path().app_data_dir().ok()?;
    let _ = std::fs::create_dir_all(&dir);
    Some(dir.join("state.json"))
}

fn load_state(app: &AppHandle) -> Option<PersistedState> {
    let path = state_file(app)?;
    let txt = std::fs::read_to_string(path).ok()?;
    serde_json::from_str(&txt).ok()
}

fn save_state(app: &AppHandle, state: &PersistedState) {
    if let Some(path) = state_file(app) {
        if let Ok(txt) = serde_json::to_string_pretty(state) {
            let _ = std::fs::write(path, txt);
        }
    }
}

fn check_due(app: &AppHandle) -> bool {
    match load_state(app).and_then(|s| s.last_check_at) {
        Some(t) => now_secs().saturating_sub(t) >= CHECK_INTERVAL_SECS,
        None => true,
    }
}

// ---------------------------------------------------------------------------
// Settings (the source checkout used to launch the Electron desktop app)
// ---------------------------------------------------------------------------

#[derive(Serialize, Deserialize, Clone, Default)]
struct Settings {
    /// Path to a DeepSeek Harness source checkout. The Electron desktop app is
    /// not shipped with this panel - it runs from that checkout via
    /// `pnpm run dev:desktop`.
    desktop_source_dir: Option<String>,
}

fn settings_file(app: &AppHandle) -> Option<PathBuf> {
    let dir = app.path().app_data_dir().ok()?;
    let _ = std::fs::create_dir_all(&dir);
    Some(dir.join("settings.json"))
}

fn load_settings(app: &AppHandle) -> Settings {
    settings_file(app)
        .and_then(|p| std::fs::read_to_string(p).ok())
        .and_then(|t| serde_json::from_str(&t).ok())
        .unwrap_or_default()
}

fn save_settings(app: &AppHandle, settings: &Settings) {
    if let Some(path) = settings_file(app) {
        if let Ok(txt) = serde_json::to_string_pretty(settings) {
            let _ = std::fs::write(path, txt);
        }
    }
}

/// A source checkout is usable once it has a manifest and installed deps.
fn source_dir_problem(dir: &str) -> Option<String> {
    let root = PathBuf::from(dir);
    if !root.is_dir() {
        return Some(format!("目录不存在：{dir}"));
    }
    if !root.join("package.json").is_file() {
        return Some(format!("{dir} 里没有 package.json，不像是 DeepSeek Harness 源码"));
    }
    if !root.join("node_modules").is_dir() {
        return Some(format!("{dir} 还没装依赖，请先在终端执行 pnpm install"));
    }
    None
}

/// Stream a child's stdout/stderr into the panel's embedded terminal.
fn pipe_to_terminal(app: &AppHandle, child: &mut std::process::Child) {
    if let Some(out) = child.stdout.take() {
        let handle = app.clone();
        std::thread::spawn(move || {
            for line in BufReader::new(out).lines().map_while(Result::ok) {
                let _ = handle.emit("harness-output", line);
            }
        });
    }
    if let Some(err) = child.stderr.take() {
        let handle = app.clone();
        std::thread::spawn(move || {
            for line in BufReader::new(err).lines().map_while(Result::ok) {
                let _ = handle.emit("harness-output", line);
            }
        });
    }
}

// ---------------------------------------------------------------------------
// Tray
// ---------------------------------------------------------------------------

/// Windows tracks the taskbar theme separately from the app theme
/// (`SystemUsesLightTheme`), and that is what the tray icon has to blend with.
#[cfg(windows)]
fn taskbar_is_light() -> bool {
    use winreg::enums::HKEY_CURRENT_USER;
    use winreg::RegKey;
    RegKey::predef(HKEY_CURRENT_USER)
        .open_subkey(r"Software\Microsoft\Windows\CurrentVersion\Themes\Personalize")
        .and_then(|k| k.get_value::<u32, _>("SystemUsesLightTheme"))
        .map(|v| v == 1)
        .unwrap_or(false)
}

#[cfg(not(windows))]
fn taskbar_is_light() -> bool {
    false
}

fn tray_image(running: bool, light: bool) -> tauri::image::Image<'static> {
    let bytes: &'static [u8] = match (running, light) {
        (false, false) => TRAY_OFF_DARK,
        (true, false) => TRAY_ON_DARK,
        (false, true) => TRAY_OFF_LIGHT,
        (true, true) => TRAY_ON_LIGHT,
    };
    tauri::image::Image::from_bytes(bytes).expect("embedded tray icon must decode")
}

/// Tray icon + tooltip together cover the two things worth glancing at:
/// whether the harness is up, and whether dsh can be updated.
fn refresh_tray(app: &AppHandle) {
    let Some(tray) = app.tray_by_id(TRAY_ID) else {
        return;
    };
    let running = HARNESS_RUNNING.load(Ordering::Relaxed);
    let light = TASKBAR_LIGHT.load(Ordering::Relaxed);
    let _ = tray.set_icon(Some(tray_image(running, light)));

    let run_text = if running {
        "harness 运行中"
    } else {
        "harness 未启动"
    };
    let ver_text = match load_state(app) {
        Some(s) => match (&s.last_local_version, &s.last_latest_version) {
            (Some(local), Some(latest)) if is_newer(latest, Some(local)) => {
                format!("有新版本 {latest}")
            }
            (Some(local), _) => format!("dsh {local}"),
            _ => "dsh 版本未知".to_string(),
        },
        None => "尚未检查更新".to_string(),
    };
    let _ = tray.set_tooltip(Some(&format!("DSH Panel · {run_text} · {ver_text}")));
}

fn show_panel(app: &AppHandle) {
    if let Some(w) = app.get_webview_window("main") {
        let _ = w.show();
        let _ = w.unminimize();
        let _ = w.set_focus();
    }
}

// ---------------------------------------------------------------------------
// Actions
// ---------------------------------------------------------------------------

async fn port_alive(url: &str) -> bool {
    let Ok(client) = reqwest::Client::builder()
        .timeout(Duration::from_millis(1500))
        .build()
    else {
        return false;
    };
    // Any HTTP answer at all means something is serving there.
    client.get(url).send().await.is_ok()
}

/// The button is "open the harness", not "start a server":
/// already serving → just open a browser tab; otherwise boot it in a new console.
async fn open_harness_inner(port: u16) -> ActionResult {
    let url = format!("http://127.0.0.1:{}/", port);

    if port_alive(&url).await {
        return match Command::new("cmd")
            .args(["/c", "start", "", &url])
            .creation_flags(CREATE_NO_WINDOW)
            .spawn()
        {
            Ok(_) => ActionResult {
                ok: true,
                action: "browser".into(),
                message: format!("harness 已在运行，已打开浏览器 {url}"),
                output: String::new(),
            },
            Err(e) => ActionResult {
                ok: false,
                action: "browser".into(),
                message: format!("打开浏览器失败: {e}"),
                output: String::new(),
            },
        };
    }

    let line = format!("dsh web --port {port}");
    match Command::new("cmd")
        .args(["/c", "start", "", "cmd", "/k", &line])
        .creation_flags(CREATE_NEW_CONSOLE)
        .spawn()
    {
        Ok(_) => ActionResult {
            ok: true,
            action: "started".into(),
            message: format!("已在新终端窗口启动 dsh web --port {port}"),
            output: String::new(),
        },
        Err(e) => ActionResult {
            ok: false,
            action: "started".into(),
            message: format!("启动 harness 失败: {e}"),
            output: String::new(),
        },
    }
}

async fn upgrade_inner() -> ActionResult {
    let local = read_local();
    let Some(node_dir) = local.node_dir.clone() else {
        return ActionResult {
            ok: false,
            action: "upgrade".into(),
            message: "找不到 Node 目录，无法升级".into(),
            output: String::new(),
        };
    };

    let dir = PathBuf::from(&node_dir);
    let npm_cmd = dir.join("npm.cmd");
    if !npm_cmd.is_file() {
        return ActionResult {
            ok: false,
            action: "upgrade".into(),
            message: format!("{} 不存在", npm_cmd.display()),
            output: String::new(),
        };
    }

    // Put the active Node dir first on PATH and run there, so `npm` resolves to
    // this nvm version's npm rather than whatever else is on PATH.
    let new_path = match std::env::var("PATH") {
        Ok(p) => format!("{node_dir};{p}"),
        Err(_) => node_dir.clone(),
    };

    let joined = tauri::async_runtime::spawn_blocking(move || {
        Command::new("cmd")
            .arg("/c")
            .arg("npm")
            .args(["install", "-g", &format!("{PKG_NAME}@latest")])
            .current_dir(&dir)
            .env("PATH", new_path)
            .creation_flags(CREATE_NO_WINDOW)
            .output()
    })
    .await;

    match joined {
        Ok(Ok(out)) => {
            let stdout = String::from_utf8_lossy(&out.stdout).to_string();
            let stderr = String::from_utf8_lossy(&out.stderr).to_string();
            let combined = format!("{stdout}{stderr}");

            if out.status.success() {
                let after = read_local();
                ActionResult {
                    ok: true,
                    action: "upgrade".into(),
                    message: format!(
                        "升级完成，当前版本 {}。正在运行的 harness 需要重启才会生效",
                        after.dsh_version.unwrap_or_else(|| "未知".into())
                    ),
                    output: combined,
                }
            } else {
                let locked = ["EBUSY", "EPERM", "operation not permitted", "resource busy"]
                    .iter()
                    .any(|k| combined.contains(k));
                ActionResult {
                    ok: false,
                    action: "upgrade".into(),
                    message: if locked {
                        "升级失败：文件被占用（harness 多半正在运行）。请先关掉正在运行的 harness 再试".into()
                    } else {
                        format!("升级失败，npm 退出码 {:?}", out.status.code())
                    },
                    output: combined,
                }
            }
        }
        Ok(Err(e)) => ActionResult {
            ok: false,
            action: "upgrade".into(),
            message: format!("无法执行 npm: {e}"),
            output: String::new(),
        },
        Err(e) => ActionResult {
            ok: false,
            action: "upgrade".into(),
            message: format!("升级任务失败: {e}"),
            output: String::new(),
        },
    }
}

// ---------------------------------------------------------------------------
// Commands
// ---------------------------------------------------------------------------

#[tauri::command]
fn get_local_info() -> LocalInfo {
    read_local()
}

#[tauri::command]
async fn check_update(app: AppHandle) -> UpdateInfo {
    run_check(&app).await
}

#[tauri::command]
async fn upgrade_dsh() -> ActionResult {
    upgrade_inner().await
}

#[tauri::command]
async fn open_harness(port: Option<u16>) -> ActionResult {
    open_harness_inner(port.unwrap_or(DEFAULT_HARNESS_PORT)).await
}

/// Start the harness *inside* the panel: its output is piped to the UI instead of
/// the harness opening in a separate console window.
#[tauri::command]
async fn start_harness_inline(app: AppHandle, port: Option<u16>) -> ActionResult {
    let port = port.unwrap_or(DEFAULT_HARNESS_PORT);
    let url = harness_url(port);

    if port_alive(&url).await {
        let _ = Command::new("cmd")
            .args(["/c", "start", "", &url])
            .creation_flags(CREATE_NO_WINDOW)
            .spawn();
        let msg = format!("harness 已在运行，已打开浏览器 {url}");
        let _ = app.emit("harness-output", msg.clone());
        return ActionResult {
            ok: true,
            action: "browser".into(),
            message: msg,
            output: String::new(),
        };
    }

    let mut child = match Command::new("cmd")
        .args(["/c", "dsh", "web", "--port", &port.to_string()])
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .creation_flags(CREATE_NO_WINDOW)
        .spawn()
    {
        Ok(c) => c,
        Err(e) => {
            return ActionResult {
                ok: false,
                action: "inline".into(),
                message: format!("启动失败: {e}"),
                output: String::new(),
            }
        }
    };

    let _ = app.emit("harness-output", format!("$ dsh web --port {port}"));

    if let Some(out) = child.stdout.take() {
        let handle = app.clone();
        std::thread::spawn(move || {
            for line in BufReader::new(out).lines().map_while(Result::ok) {
                let _ = handle.emit("harness-output", line);
            }
        });
    }
    if let Some(err) = child.stderr.take() {
        let handle = app.clone();
        std::thread::spawn(move || {
            for line in BufReader::new(err).lines().map_while(Result::ok) {
                let _ = handle.emit("harness-output", line);
            }
        });
    }

    *HARNESS_CHILD.get_or_init(|| Mutex::new(None)).lock().unwrap() = Some(child);

    ActionResult {
        ok: true,
        action: "inline".into(),
        message: format!("已在面板内启动 dsh web --port {port}，输出见下方终端"),
        output: String::new(),
    }
}

/// PIDs LISTENING on a TCP port, via Windows `netstat -ano`.
fn pids_on_port(port: u16) -> Vec<u32> {
    let Ok(out) = Command::new("cmd")
        .args(["/c", "netstat", "-ano", "-p", "tcp"])
        .creation_flags(CREATE_NO_WINDOW)
        .output()
    else {
        return Vec::new();
    };
    let text = String::from_utf8_lossy(&out.stdout);
    let suffix = format!(":{port}");
    let mut pids: Vec<u32> = Vec::new();
    for line in text.lines() {
        if !line.contains("LISTENING") {
            continue;
        }
        let cols: Vec<&str> = line.split_whitespace().collect();
        if cols.len() < 5 || !cols[1].ends_with(&suffix) {
            continue;
        }
        if let Ok(pid) = cols[4].parse::<u32>() {
            if !pids.contains(&pid) {
                pids.push(pid);
            }
        }
    }
    pids
}

/// Image name for a PID. Used so we never kill something unrelated that merely
/// happens to hold the port.
fn process_name(pid: u32) -> Option<String> {
    let out = Command::new("cmd")
        .args([
            "/c",
            "tasklist",
            "/FI",
            &format!("PID eq {pid}"),
            "/FO",
            "CSV",
            "/NH",
        ])
        .creation_flags(CREATE_NO_WINDOW)
        .output()
        .ok()?;
    let text = String::from_utf8_lossy(&out.stdout);
    let first = text.lines().next()?.trim().to_string();
    if first.is_empty() || first.starts_with("INFO:") {
        return None;
    }
    first.split(',').next().map(|s| s.trim_matches('"').to_string())
}

/// Stop the harness. Prefers the child the panel launched; otherwise stops
/// whatever node process is listening on the port (that is how a harness started
/// elsewhere - a terminal, another tool - gets stopped from here).
#[tauri::command]
fn stop_harness(port: Option<u16>) -> ActionResult {
    let port = port.unwrap_or(DEFAULT_HARNESS_PORT);

    // 1) A harness the panel launched: kill our own subtree (panel -> cmd -> node).
    //    /T is safe here because those processes sit below us.
    if let Some(mut child) = HARNESS_CHILD
        .get_or_init(|| Mutex::new(None))
        .lock()
        .unwrap()
        .take()
    {
        let pid = child.id();
        let _ = Command::new("cmd")
            .args(["/c", "taskkill", "/PID", &pid.to_string(), "/F", "/T"])
            .creation_flags(CREATE_NO_WINDOW)
            .output();
        let _ = child.wait();
        return ActionResult {
            ok: true,
            action: "stop".into(),
            message: "已停止面板启动的 Web 端".into(),
            output: String::new(),
        };
    }

    // 2) A harness started elsewhere.
    //
    //    NEVER pass /T here. When the harness is what launched this panel (the
    //    panel then sits below it in the process tree) /T would kill the panel
    //    along with the target - the stop button would take the panel down too.
    let pids = pids_on_port(port);
    if pids.is_empty() {
        return ActionResult {
            ok: false,
            action: "stop".into(),
            message: format!("端口 {port} 上没有在监听的进程"),
            output: String::new(),
        };
    }

    let me = std::process::id();
    let mut killed: Vec<u32> = Vec::new();
    let mut refused: Vec<u32> = Vec::new();
    for pid in pids {
        if pid == me {
            refused.push(pid);
            continue;
        }
        let is_node = process_name(pid)
            .map(|n| n.eq_ignore_ascii_case("node.exe"))
            .unwrap_or(false);
        if !is_node {
            refused.push(pid);
            continue;
        }
        let ok = Command::new("cmd")
            .args(["/c", "taskkill", "/PID", &pid.to_string(), "/F"])
            .creation_flags(CREATE_NO_WINDOW)
            .output()
            .map(|o| o.status.success())
            .unwrap_or(false);
        if ok {
            killed.push(pid);
        } else {
            refused.push(pid);
        }
    }

    let join = |v: &[u32]| v.iter().map(|p| p.to_string()).collect::<Vec<_>>().join(", ");
    ActionResult {
        ok: !killed.is_empty(),
        action: "stop".into(),
        message: if !killed.is_empty() {
            format!("已停止占用端口 {port} 的 harness（PID {}）", join(&killed))
        } else {
            format!("端口 {port} 被非 node 进程占用（PID {}），没有动它", join(&refused))
        },
        output: String::new(),
    }
}

/// Whether the desktop app the panel launched is still alive.
#[tauri::command]
fn desktop_running() -> bool {
    match DESKTOP_CHILD
        .get_or_init(|| Mutex::new(None))
        .lock()
        .unwrap()
        .as_mut()
    {
        Some(child) => matches!(child.try_wait(), Ok(None)),
        None => false,
    }
}

#[tauri::command]
fn get_settings(app: AppHandle) -> Settings {
    load_settings(&app)
}

/// Save (or clear) the source checkout the desktop app is launched from.
#[tauri::command]
fn set_desktop_source_dir(app: AppHandle, dir: Option<String>) -> ActionResult {
    let mut settings = load_settings(&app);
    settings.desktop_source_dir = dir
        .map(|d| d.trim().to_string())
        .filter(|d| !d.is_empty());
    save_settings(&app, &settings);

    ActionResult {
        ok: true,
        action: "settings".into(),
        message: match &settings.desktop_source_dir {
            Some(d) => format!("已保存源码目录：{d}"),
            None => "已清除源码目录".into(),
        },
        output: String::new(),
    }
}

/// Launch the Electron desktop app FROM SOURCE. `dev:desktop` builds the host,
/// client bundles, web frontend and Electron shell first, so the first run is slow.
#[tauri::command]
async fn start_desktop_app(app: AppHandle) -> ActionResult {
    let Some(dir) = load_settings(&app).desktop_source_dir else {
        return ActionResult {
            ok: false,
            action: "desktop".into(),
            message: "还没配置源码目录，先在下面的「桌面端源码目录」里选一个".into(),
            output: String::new(),
        };
    };

    if let Some(problem) = source_dir_problem(&dir) {
        return ActionResult {
            ok: false,
            action: "desktop".into(),
            message: problem,
            output: String::new(),
        };
    }

    let root = PathBuf::from(&dir);
    let _ = app.emit("harness-output", format!("$ cd {dir}"));
    let _ = app.emit("harness-output", "$ pnpm run dev:desktop");

    let mut child = match Command::new("cmd")
        .args(["/c", "pnpm", "run", "dev:desktop"])
        .current_dir(&root)
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .creation_flags(CREATE_NO_WINDOW)
        .spawn()
    {
        Ok(c) => c,
        Err(e) => {
            return ActionResult {
                ok: false,
                action: "desktop".into(),
                message: format!("启动失败: {e}"),
                output: String::new(),
            }
        }
    };

    pipe_to_terminal(&app, &mut child);
    *DESKTOP_CHILD.get_or_init(|| Mutex::new(None)).lock().unwrap() = Some(child);

    ActionResult {
        ok: true,
        action: "desktop".into(),
        message: "已在面板内启动 Electron 桌面端（首次会构建，需要几分钟）".into(),
        output: String::new(),
    }
}

#[tauri::command]
fn stop_desktop_app() -> ActionResult {
    let stopped = DESKTOP_CHILD
        .get_or_init(|| Mutex::new(None))
        .lock()
        .unwrap()
        .take()
        .map(|mut c| {
            let _ = c.kill();
            let _ = c.wait();
            true
        })
        .unwrap_or(false);

    ActionResult {
        ok: stopped,
        action: "stop".into(),
        message: if stopped {
            "已停止面板启动的桌面端".into()
        } else {
            "没有由面板启动的桌面端".into()
        },
        output: String::new(),
    }
}

/// Lets the panel render the harness state immediately instead of waiting for
/// the next poll tick.
#[tauri::command]
fn harness_running() -> bool {
    HARNESS_RUNNING.load(Ordering::Relaxed)
}

#[tauri::command]
fn quit_app(app: AppHandle) {
    app.exit(0);
}

// ---------------------------------------------------------------------------
// Bootstrap
// ---------------------------------------------------------------------------

/// True when this process belongs to a Windows Job Object.
#[cfg(windows)]
fn in_any_job() -> bool {
    #[link(name = "kernel32")]
    extern "system" {
        fn GetCurrentProcess() -> *mut core::ffi::c_void;
        fn IsProcessInJob(
            process: *mut core::ffi::c_void,
            job: *mut core::ffi::c_void,
            result: *mut i32,
        ) -> i32;
    }
    let mut result: i32 = 0;
    // A null job handle asks "is it in ANY job?".
    let ok = unsafe { IsProcessInJob(GetCurrentProcess(), std::ptr::null_mut(), &mut result) };
    ok != 0 && result != 0
}

#[cfg(not(windows))]
fn in_any_job() -> bool {
    false
}

/// The harness runs its children inside a Windows Job Object, so a panel started
/// from a harness session dies together with the harness - no `taskkill` flag can
/// prevent that, because closing the job terminates every member process.
///
/// So: if we find ourselves inside any job, relaunch through explorer.exe (which
/// is not in that job) and let this instance exit. The env marker keeps it to one
/// hop, so a genuinely orphaned panel does not loop forever.
#[cfg(windows)]
fn detach_from_job_if_needed() {
    if std::env::var_os("DSH_PANEL_DETACHED").is_some() || !in_any_job() {
        return;
    }
    let Ok(exe) = std::env::current_exe() else {
        return;
    };
    let spawned = std::process::Command::new("explorer.exe")
        .arg(&exe)
        .env("DSH_PANEL_DETACHED", "1")
        .spawn()
        .is_ok();
    if spawned {
        std::process::exit(0);
    }
}

#[cfg(not(windows))]
fn detach_from_job_if_needed() {}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    detach_from_job_if_needed();
    tauri::Builder::default()
        .plugin(tauri_plugin_dialog::init())
        .setup(|app| {
            let open_panel = MenuItem::with_id(app, "open_panel", "打开面板", true, None::<&str>)?;
            let launch = MenuItem::with_id(app, "launch", "打开 Harness", true, None::<&str>)?;
            let check = MenuItem::with_id(app, "check", "立即检查更新", true, None::<&str>)?;
            let quit = MenuItem::with_id(app, "quit", "退出", true, None::<&str>)?;
            let menu = Menu::with_items(app, &[&open_panel, &launch, &check, &quit])?;

            TrayIconBuilder::with_id(TRAY_ID)
                .icon(tray_image(false, taskbar_is_light()))
                .tooltip("DSH Panel")
                .menu(&menu)
                .show_menu_on_left_click(false)
                .on_menu_event(|app, event| match event.id().as_ref() {
                    "quit" => app.exit(0),
                    "open_panel" => show_panel(app),
                    "launch" => {
                        tauri::async_runtime::spawn(async move {
                            let _ = open_harness_inner(DEFAULT_HARNESS_PORT).await;
                        });
                    }
                    "check" => {
                        let app = app.clone();
                        tauri::async_runtime::spawn(async move {
                            let info = run_check(&app).await;
                            let _ = app.emit("update-checked", &info);
                        });
                    }
                    _ => {}
                })
                .on_tray_icon_event(|tray, event| {
                    if let TrayIconEvent::Click {
                        button: MouseButton::Left,
                        button_state: MouseButtonState::Up,
                        ..
                    } = event
                    {
                        show_panel(tray.app_handle());
                    }
                })
                .build(app)?;

            // Background sweep: checks on startup, then at most once every 24h.
            let handle = app.handle().clone();
            std::thread::spawn(move || loop {
                if check_due(&handle) {
                    let info = tauri::async_runtime::block_on(run_check(&handle));
                    let _ = handle.emit("update-checked", &info);
                }
                std::thread::sleep(Duration::from_secs(3600));
            });

            // Poll the harness port so the tray icon reflects whether it is really
            // up. Repaints only when the state flips, plus once at startup.
            let handle = app.handle().clone();
            std::thread::spawn(move || {
                let url = format!("http://127.0.0.1:{}/", DEFAULT_HARNESS_PORT);
                let mut first = true;
                loop {
                    let alive = tauri::async_runtime::block_on(port_alive(&url));
                    let light = taskbar_is_light();
                    // Both swaps must run, so use non-short-circuiting `|`.
                    let changed = (HARNESS_RUNNING.swap(alive, Ordering::Relaxed) != alive)
                        | (TASKBAR_LIGHT.swap(light, Ordering::Relaxed) != light);
                    if changed || first {
                        first = false;
                        refresh_tray(&handle);
                        let _ = handle.emit("harness-state", alive);
                    }
                    std::thread::sleep(Duration::from_secs(HARNESS_POLL_SECS));
                }
            });

            Ok(())
        })
        // Tray-resident: closing the window hides it instead of quitting.
        .on_window_event(|window, event| {
            if let tauri::WindowEvent::CloseRequested { api, .. } = event {
                api.prevent_close();
                let _ = window.hide();
            }
        })
        .invoke_handler(tauri::generate_handler![
            get_local_info,
            check_update,
            upgrade_dsh,
            open_harness,
            start_harness_inline,
            stop_harness,
            get_settings,
            set_desktop_source_dir,
            start_desktop_app,
            stop_desktop_app,
            desktop_running,
            harness_running,
            quit_app
        ])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
