use std::collections::HashMap;
use std::io::{BufRead, BufReader};
use std::os::windows::process::CommandExt;
use std::path::PathBuf;
use std::process::{Command, Stdio};
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::{Mutex, OnceLock};
use std::time::{Duration, SystemTime, UNIX_EPOCH};

use chrono::Datelike;
use serde::{Deserialize, Serialize};
use tauri::menu::{Menu, MenuItem};
use tauri::tray::{MouseButton, MouseButtonState, TrayIconBuilder, TrayIconEvent};
use tauri::{AppHandle, Emitter, Manager};

/// The npm package that ships the harness.
const PKG_NAME: &str = "@deepseek-ai/dsh";
/// Same package, percent-encoded the way a registry metadata URL expects it.
const PKG_URL_PATH: &str = "@deepseek-ai%2Fdsh";
const DEFAULT_REGISTRY: &str = "https://registry.npmmirror.com";
/// "once a day" — 24h between automatic checks.
const CHECK_INTERVAL_SECS: u64 = 24 * 60 * 60;
/// The port this machine's harness UI is normally served on.
const DEFAULT_HARNESS_PORT: u16 = 3080;
const TRAY_ID: &str = "main-tray";

/// Tray icons are the app logo: colour = running, greyscale = stopped, one set
/// per taskbar theme. Generated by tools/make_icons.py.
const TRAY_OFF_DARK: &[u8] = include_bytes!("../icons-tray/tray-stopped-dark.png");
const TRAY_ON_DARK: &[u8] = include_bytes!("../icons-tray/tray-running-dark.png");
const TRAY_OFF_LIGHT: &[u8] = include_bytes!("../icons-tray/tray-stopped-light.png");
const TRAY_ON_LIGHT: &[u8] = include_bytes!("../icons-tray/tray-running-light.png");
/// How often the tray polls the harness port and the taskbar theme.
const HARNESS_POLL_SECS: u64 = 10;
/// Written by the poller thread, read when refreshing the tray.
static HARNESS_RUNNING: AtomicBool = AtomicBool::new(false);
/// Whether the taskbar is light (SystemUsesLightTheme), also set by the poller.
static TASKBAR_LIGHT: AtomicBool = AtomicBool::new(false);
/// The harness process started from inside the panel. Kept so its pipes stay
/// alive; dropping this handle does NOT kill the child process.
static HARNESS_CHILD: OnceLock<Mutex<Option<std::process::Child>>> = OnceLock::new();
/// The Electron desktop app started from source; same deal.
static DESKTOP_CHILD: OnceLock<Mutex<Option<std::process::Child>>> = OnceLock::new();
/// The in-flight `dsh plugin ...` (pnpm) process, if any.
static PLUGIN_CHILD: OnceLock<Mutex<Option<std::process::Child>>> = OnceLock::new();

fn harness_url(port: u16) -> String {
    format!("http://127.0.0.1:{port}/")
}

// Windows process creation flags.
const CREATE_NO_WINDOW: u32 = 0x0800_0000;
const CREATE_NEW_CONSOLE: u32 = 0x0000_0010;

// ---------------------------------------------------------------------------
// Data shapes handed to the frontend
// ---------------------------------------------------------------------------

#[derive(Serialize, Clone)]
struct LocalInfo {
    ok: bool,
    dsh_version: Option<String>,
    node_dir: Option<String>,
    node_version: Option<String>,
    error: Option<String>,
}

#[derive(Serialize, Clone)]
struct UpdateInfo {
    ok: bool,
    local_version: Option<String>,
    latest_version: Option<String>,
    has_update: bool,
    registry: String,
    checked_at: u64,
    error: Option<String>,
}

#[derive(Serialize, Clone)]
struct ActionResult {
    ok: bool,
    action: String,
    message: String,
    output: String,
}

#[derive(Serialize, Deserialize, Clone, Default)]
struct PersistedState {
    last_check_at: Option<u64>,
    last_latest_version: Option<String>,
    last_local_version: Option<String>,
}

// ---------------------------------------------------------------------------
// Local install discovery
// ---------------------------------------------------------------------------

fn now_secs() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0)
}

/// Strip the `\\?\` prefix `canonicalize` adds on Windows.
fn clean_path(p: PathBuf) -> PathBuf {
    let s = p.to_string_lossy().to_string();
    match s.strip_prefix(r"\\?\") {
        Some(rest) => PathBuf::from(rest),
        None => p,
    }
}

/// Locate the active Node install by finding `dsh.cmd` on PATH.
///
/// npm puts its global shims directly in the Node install root, so the directory
/// holding `dsh.cmd` *is* the Node root for whichever nvm version is active.
/// This tracks `nvm use` automatically — no hardcoded nvm paths.
fn find_node_dir() -> Option<PathBuf> {
    let path = std::env::var_os("PATH")?;
    for dir in std::env::split_paths(&path) {
        if dir.join("dsh.cmd").is_file() {
            return Some(dir);
        }
    }
    None
}

fn read_local() -> LocalInfo {
    let Some(node_dir) = find_node_dir() else {
        return LocalInfo {
            ok: false,
            dsh_version: None,
            node_dir: None,
            node_version: None,
            error: Some(
                "PATH 上找不到 dsh.cmd：dsh 可能没装，或当前 nvm 版本里没有它".to_string(),
            ),
        };
    };

    let pkg = node_dir
        .join("node_modules")
        .join("@deepseek-ai")
        .join("dsh")
        .join("package.json");

    let installed = std::fs::read_to_string(&pkg)
        .ok()
        .and_then(|t| serde_json::from_str::<serde_json::Value>(&t).ok())
        .and_then(|v| {
            v.get("version")
                .and_then(|x| x.as_str())
                .map(|s| s.to_string())
        });

    // Directory name of the resolved junction, e.g. v24.9.0
    let node_version = std::fs::canonicalize(&node_dir)
        .map(clean_path)
        .ok()
        .and_then(|p| p.file_name().map(|n| n.to_string_lossy().to_string()))
        .filter(|n| n.starts_with('v'));

    LocalInfo {
        ok: installed.is_some(),
        error: if installed.is_none() {
            Some(format!("找到 Node 目录，但读不到 {}", pkg.display()))
        } else {
            None
        },
        dsh_version: installed,
        node_dir: Some(node_dir.to_string_lossy().to_string()),
        node_version,
    }
}

/// Respect the user's npm registry (npmmirror on this machine) so the version we
/// report is the one that can actually be installed.
fn read_registry() -> String {
    if let Some(home) = std::env::var_os("USERPROFILE") {
        let npmrc = PathBuf::from(home).join(".npmrc");
        if let Ok(txt) = std::fs::read_to_string(&npmrc) {
            for line in txt.lines() {
                let line = line.trim();
                if let Some(rest) = line.strip_prefix("registry=") {
                    let v = rest.trim().trim_end_matches('/');
                    if !v.is_empty() {
                        return v.to_string();
                    }
                }
            }
        }
    }
    DEFAULT_REGISTRY.to_string()
}

// ---------------------------------------------------------------------------
// Registry check
// ---------------------------------------------------------------------------

async fn fetch_latest(registry: &str) -> Result<String, String> {
    let url = format!("{}/{}", registry.trim_end_matches('/'), PKG_URL_PATH);
    let client = reqwest::Client::builder()
        .timeout(Duration::from_secs(20))
        .user_agent("dsh-panel")
        .build()
        .map_err(|e| format!("创建 HTTP 客户端失败: {e}"))?;

    let resp = client
        .get(&url)
        .send()
        .await
        .map_err(|e| format!("请求 registry 失败: {e}"))?;

    if !resp.status().is_success() {
        return Err(format!("registry 返回 HTTP {}", resp.status()));
    }

    let body: serde_json::Value = resp
        .json()
        .await
        .map_err(|e| format!("解析 registry 响应失败: {e}"))?;

    body.get("dist-tags")
        .and_then(|t| t.get("latest"))
        .and_then(|s| s.as_str())
        .map(|s| s.to_string())
        .ok_or_else(|| "registry 响应里没有 dist-tags.latest".to_string())
}

fn is_newer(latest: &str, current: Option<&str>) -> bool {
    let Some(cur) = current else { return false };
    match (
        semver::Version::parse(latest),
        semver::Version::parse(cur),
    ) {
        (Ok(l), Ok(c)) => l > c,
        _ => latest != cur,
    }
}

async fn run_check(app: &AppHandle) -> UpdateInfo {
    let local = read_local();
    let registry = read_registry();
    let now = now_secs();

    let mut info = UpdateInfo {
        ok: false,
        local_version: local.dsh_version.clone(),
        latest_version: None,
        has_update: false,
        registry: registry.clone(),
        checked_at: now,
        error: None,
    };

    if local.dsh_version.is_none() {
        info.error = local.error.clone();
        return info;
    }

    match fetch_latest(&registry).await {
        Ok(latest) => {
            info.has_update = is_newer(&latest, local.dsh_version.as_deref());
            info.latest_version = Some(latest.clone());
            info.ok = true;
            save_state(
                app,
                &PersistedState {
                    last_check_at: Some(now),
                    last_latest_version: Some(latest),
                    last_local_version: local.dsh_version,
                },
            );
            refresh_tray(app);
        }
        Err(e) => info.error = Some(e),
    }

    info
}

// ---------------------------------------------------------------------------
// Persisted state (drives the "once a day" rule)
// ---------------------------------------------------------------------------

fn state_file(app: &AppHandle) -> Option<PathBuf> {
    let dir = app.path().app_data_dir().ok()?;
    let _ = std::fs::create_dir_all(&dir);
    Some(dir.join("state.json"))
}

fn load_state(app: &AppHandle) -> Option<PersistedState> {
    let path = state_file(app)?;
    let txt = std::fs::read_to_string(path).ok()?;
    serde_json::from_str(&txt).ok()
}

fn save_state(app: &AppHandle, state: &PersistedState) {
    if let Some(path) = state_file(app) {
        if let Ok(txt) = serde_json::to_string_pretty(state) {
            let _ = std::fs::write(path, txt);
        }
    }
}

fn check_due(app: &AppHandle) -> bool {
    match load_state(app).and_then(|s| s.last_check_at) {
        Some(t) => now_secs().saturating_sub(t) >= CHECK_INTERVAL_SECS,
        None => true,
    }
}

// ---------------------------------------------------------------------------
// Settings (the source checkout used to launch the Electron desktop app)
// ---------------------------------------------------------------------------

#[derive(Serialize, Deserialize, Clone, Default)]
struct Settings {
    /// Path to a DeepSeek Harness source checkout. The Electron desktop app is
    /// not shipped with this panel - it runs from that checkout via
    /// `pnpm run dev:desktop`.
    desktop_source_dir: Option<String>,
}

fn settings_file(app: &AppHandle) -> Option<PathBuf> {
    let dir = app.path().app_data_dir().ok()?;
    let _ = std::fs::create_dir_all(&dir);
    Some(dir.join("settings.json"))
}

fn load_settings(app: &AppHandle) -> Settings {
    settings_file(app)
        .and_then(|p| std::fs::read_to_string(p).ok())
        .and_then(|t| serde_json::from_str(&t).ok())
        .unwrap_or_default()
}

fn save_settings(app: &AppHandle, settings: &Settings) {
    if let Some(path) = settings_file(app) {
        if let Ok(txt) = serde_json::to_string_pretty(settings) {
            let _ = std::fs::write(path, txt);
        }
    }
}

/// A source checkout is usable once it has a manifest and installed deps.
fn source_dir_problem(dir: &str) -> Option<String> {
    let root = PathBuf::from(dir);
    if !root.is_dir() {
        return Some(format!("目录不存在：{dir}"));
    }
    if !root.join("package.json").is_file() {
        return Some(format!("{dir} 里没有 package.json，不像是 DeepSeek Harness 源码"));
    }
    if !root.join("node_modules").is_dir() {
        return Some(format!("{dir} 还没装依赖，请先在终端执行 pnpm install"));
    }
    None
}

/// Stream a child's stdout/stderr into the panel's embedded terminal.
fn pipe_to_terminal(app: &AppHandle, child: &mut std::process::Child) {
    if let Some(out) = child.stdout.take() {
        let handle = app.clone();
        std::thread::spawn(move || {
            for line in BufReader::new(out).lines().map_while(Result::ok) {
                let _ = handle.emit("harness-output", line);
            }
        });
    }
    if let Some(err) = child.stderr.take() {
        let handle = app.clone();
        std::thread::spawn(move || {
            for line in BufReader::new(err).lines().map_while(Result::ok) {
                let _ = handle.emit("harness-output", line);
            }
        });
    }
}

// ---------------------------------------------------------------------------
// Tray
// ---------------------------------------------------------------------------

/// Windows tracks the taskbar theme separately from the app theme
/// (`SystemUsesLightTheme`), and that is what the tray icon has to blend with.
#[cfg(windows)]
fn taskbar_is_light() -> bool {
    use winreg::enums::HKEY_CURRENT_USER;
    use winreg::RegKey;
    RegKey::predef(HKEY_CURRENT_USER)
        .open_subkey(r"Software\Microsoft\Windows\CurrentVersion\Themes\Personalize")
        .and_then(|k| k.get_value::<u32, _>("SystemUsesLightTheme"))
        .map(|v| v == 1)
        .unwrap_or(false)
}

#[cfg(not(windows))]
fn taskbar_is_light() -> bool {
    false
}

fn tray_image(running: bool, light: bool) -> tauri::image::Image<'static> {
    let bytes: &'static [u8] = match (running, light) {
        (false, false) => TRAY_OFF_DARK,
        (true, false) => TRAY_ON_DARK,
        (false, true) => TRAY_OFF_LIGHT,
        (true, true) => TRAY_ON_LIGHT,
    };
    tauri::image::Image::from_bytes(bytes).expect("embedded tray icon must decode")
}

/// Tray icon + tooltip together cover the two things worth glancing at:
/// whether the harness is up, and whether dsh can be updated.
fn refresh_tray(app: &AppHandle) {
    let Some(tray) = app.tray_by_id(TRAY_ID) else {
        return;
    };
    let running = HARNESS_RUNNING.load(Ordering::Relaxed);
    let light = TASKBAR_LIGHT.load(Ordering::Relaxed);
    let _ = tray.set_icon(Some(tray_image(running, light)));

    let run_text = if running {
        "harness 运行中"
    } else {
        "harness 未启动"
    };
    let ver_text = match load_state(app) {
        Some(s) => match (&s.last_local_version, &s.last_latest_version) {
            (Some(local), Some(latest)) if is_newer(latest, Some(local)) => {
                format!("有新版本 {latest}")
            }
            (Some(local), _) => format!("dsh {local}"),
            _ => "dsh 版本未知".to_string(),
        },
        None => "尚未检查更新".to_string(),
    };
    let _ = tray.set_tooltip(Some(&format!("DSH Panel · {run_text} · {ver_text}")));
}

fn show_panel(app: &AppHandle) {
    if let Some(w) = app.get_webview_window("main") {
        let _ = w.show();
        let _ = w.unminimize();
        let _ = w.set_focus();
    }
}

// ---------------------------------------------------------------------------
// Actions
// ---------------------------------------------------------------------------

async fn port_alive(url: &str) -> bool {
    let Ok(client) = reqwest::Client::builder()
        .timeout(Duration::from_millis(1500))
        .build()
    else {
        return false;
    };
    // Any HTTP answer at all means something is serving there.
    client.get(url).send().await.is_ok()
}

/// The button is "open the harness", not "start a server":
/// already serving → just open a browser tab; otherwise boot it in a new console.
async fn open_harness_inner(port: u16) -> ActionResult {
    let url = format!("http://127.0.0.1:{}/", port);

    if port_alive(&url).await {
        return match Command::new("cmd")
            .args(["/c", "start", "", &url])
            .creation_flags(CREATE_NO_WINDOW)
            .spawn()
        {
            Ok(_) => ActionResult {
                ok: true,
                action: "browser".into(),
                message: format!("harness 已在运行，已打开浏览器 {url}"),
                output: String::new(),
            },
            Err(e) => ActionResult {
                ok: false,
                action: "browser".into(),
                message: format!("打开浏览器失败: {e}"),
                output: String::new(),
            },
        };
    }

    let line = format!("dsh web --port {port}");
    match Command::new("cmd")
        .args(["/c", "start", "", "cmd", "/k", &line])
        .creation_flags(CREATE_NEW_CONSOLE)
        .spawn()
    {
        Ok(_) => ActionResult {
            ok: true,
            action: "started".into(),
            message: format!("已在新终端窗口启动 dsh web --port {port}"),
            output: String::new(),
        },
        Err(e) => ActionResult {
            ok: false,
            action: "started".into(),
            message: format!("启动 harness 失败: {e}"),
            output: String::new(),
        },
    }
}

async fn upgrade_inner() -> ActionResult {
    let local = read_local();
    let Some(node_dir) = local.node_dir.clone() else {
        return ActionResult {
            ok: false,
            action: "upgrade".into(),
            message: "找不到 Node 目录，无法升级".into(),
            output: String::new(),
        };
    };

    let dir = PathBuf::from(&node_dir);
    let npm_cmd = dir.join("npm.cmd");
    if !npm_cmd.is_file() {
        return ActionResult {
            ok: false,
            action: "upgrade".into(),
            message: format!("{} 不存在", npm_cmd.display()),
            output: String::new(),
        };
    }

    // Put the active Node dir first on PATH and run there, so `npm` resolves to
    // this nvm version's npm rather than whatever else is on PATH.
    let new_path = match std::env::var("PATH") {
        Ok(p) => format!("{node_dir};{p}"),
        Err(_) => node_dir.clone(),
    };

    let joined = tauri::async_runtime::spawn_blocking(move || {
        Command::new("cmd")
            .arg("/c")
            .arg("npm")
            .args(["install", "-g", &format!("{PKG_NAME}@latest")])
            .current_dir(&dir)
            .env("PATH", new_path)
            .creation_flags(CREATE_NO_WINDOW)
            .output()
    })
    .await;

    match joined {
        Ok(Ok(out)) => {
            let stdout = String::from_utf8_lossy(&out.stdout).to_string();
            let stderr = String::from_utf8_lossy(&out.stderr).to_string();
            let combined = format!("{stdout}{stderr}");

            if out.status.success() {
                let after = read_local();
                ActionResult {
                    ok: true,
                    action: "upgrade".into(),
                    message: format!(
                        "升级完成，当前版本 {}。正在运行的 harness 需要重启才会生效",
                        after.dsh_version.unwrap_or_else(|| "未知".into())
                    ),
                    output: combined,
                }
            } else {
                let locked = ["EBUSY", "EPERM", "operation not permitted", "resource busy"]
                    .iter()
                    .any(|k| combined.contains(k));
                ActionResult {
                    ok: false,
                    action: "upgrade".into(),
                    message: if locked {
                        "升级失败：文件被占用（harness 多半正在运行）。请先关掉正在运行的 harness 再试".into()
                    } else {
                        format!("升级失败，npm 退出码 {:?}", out.status.code())
                    },
                    output: combined,
                }
            }
        }
        Ok(Err(e)) => ActionResult {
            ok: false,
            action: "upgrade".into(),
            message: format!("无法执行 npm: {e}"),
            output: String::new(),
        },
        Err(e) => ActionResult {
            ok: false,
            action: "upgrade".into(),
            message: format!("升级任务失败: {e}"),
            output: String::new(),
        },
    }
}

// ---------------------------------------------------------------------------
// Commands
// ---------------------------------------------------------------------------

#[tauri::command]
fn get_local_info() -> LocalInfo {
    read_local()
}

#[tauri::command]
async fn check_update(app: AppHandle) -> UpdateInfo {
    run_check(&app).await
}

#[tauri::command]
async fn upgrade_dsh() -> ActionResult {
    upgrade_inner().await
}

#[tauri::command]
async fn open_harness(port: Option<u16>) -> ActionResult {
    open_harness_inner(port.unwrap_or(DEFAULT_HARNESS_PORT)).await
}

/// Start the harness *inside* the panel: its output is piped to the UI instead of
/// the harness opening in a separate console window.
#[tauri::command]
async fn start_harness_inline(app: AppHandle, port: Option<u16>) -> ActionResult {
    let port = port.unwrap_or(DEFAULT_HARNESS_PORT);
    let url = harness_url(port);

    if port_alive(&url).await {
        let _ = Command::new("cmd")
            .args(["/c", "start", "", &url])
            .creation_flags(CREATE_NO_WINDOW)
            .spawn();
        let msg = format!("harness 已在运行，已打开浏览器 {url}");
        let _ = app.emit("harness-output", msg.clone());
        return ActionResult {
            ok: true,
            action: "browser".into(),
            message: msg,
            output: String::new(),
        };
    }

    let mut child = match Command::new("cmd")
        .args(["/c", "dsh", "web", "--port", &port.to_string()])
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .creation_flags(CREATE_NO_WINDOW)
        .spawn()
    {
        Ok(c) => c,
        Err(e) => {
            return ActionResult {
                ok: false,
                action: "inline".into(),
                message: format!("启动失败: {e}"),
                output: String::new(),
            }
        }
    };

    let _ = app.emit("harness-output", format!("$ dsh web --port {port}"));

    if let Some(out) = child.stdout.take() {
        let handle = app.clone();
        std::thread::spawn(move || {
            for line in BufReader::new(out).lines().map_while(Result::ok) {
                let _ = handle.emit("harness-output", line);
            }
        });
    }
    if let Some(err) = child.stderr.take() {
        let handle = app.clone();
        std::thread::spawn(move || {
            for line in BufReader::new(err).lines().map_while(Result::ok) {
                let _ = handle.emit("harness-output", line);
            }
        });
    }

    *HARNESS_CHILD.get_or_init(|| Mutex::new(None)).lock().unwrap() = Some(child);

    ActionResult {
        ok: true,
        action: "inline".into(),
        message: format!("已在面板内启动 dsh web --port {port}，输出见下方终端"),
        output: String::new(),
    }
}

/// PIDs LISTENING on a TCP port, via Windows `netstat -ano`.
fn pids_on_port(port: u16) -> Vec<u32> {
    let Ok(out) = Command::new("cmd")
        .args(["/c", "netstat", "-ano", "-p", "tcp"])
        .creation_flags(CREATE_NO_WINDOW)
        .output()
    else {
        return Vec::new();
    };
    let text = String::from_utf8_lossy(&out.stdout);
    let suffix = format!(":{port}");
    let mut pids: Vec<u32> = Vec::new();
    for line in text.lines() {
        if !line.contains("LISTENING") {
            continue;
        }
        let cols: Vec<&str> = line.split_whitespace().collect();
        if cols.len() < 5 || !cols[1].ends_with(&suffix) {
            continue;
        }
        if let Ok(pid) = cols[4].parse::<u32>() {
            if !pids.contains(&pid) {
                pids.push(pid);
            }
        }
    }
    pids
}

/// Image name for a PID. Used so we never kill something unrelated that merely
/// happens to hold the port.
fn process_name(pid: u32) -> Option<String> {
    let out = Command::new("cmd")
        .args([
            "/c",
            "tasklist",
            "/FI",
            &format!("PID eq {pid}"),
            "/FO",
            "CSV",
            "/NH",
        ])
        .creation_flags(CREATE_NO_WINDOW)
        .output()
        .ok()?;
    let text = String::from_utf8_lossy(&out.stdout);
    let first = text.lines().next()?.trim().to_string();
    if first.is_empty() || first.starts_with("INFO:") {
        return None;
    }
    first.split(',').next().map(|s| s.trim_matches('"').to_string())
}

/// Stop the harness. Prefers the child the panel launched; otherwise stops
/// whatever node process is listening on the port (that is how a harness started
/// elsewhere - a terminal, another tool - gets stopped from here).
#[tauri::command]
fn stop_harness(port: Option<u16>) -> ActionResult {
    let port = port.unwrap_or(DEFAULT_HARNESS_PORT);

    // 1) A harness the panel launched: kill our own subtree (panel -> cmd -> node).
    //    /T is safe here because those processes sit below us.
    if let Some(mut child) = HARNESS_CHILD
        .get_or_init(|| Mutex::new(None))
        .lock()
        .unwrap()
        .take()
    {
        let pid = child.id();
        let _ = Command::new("cmd")
            .args(["/c", "taskkill", "/PID", &pid.to_string(), "/F", "/T"])
            .creation_flags(CREATE_NO_WINDOW)
            .output();
        let _ = child.wait();
        return ActionResult {
            ok: true,
            action: "stop".into(),
            message: "已停止面板启动的 Web 端".into(),
            output: String::new(),
        };
    }

    // 2) A harness started elsewhere.
    //
    //    NEVER pass /T here. When the harness is what launched this panel (the
    //    panel then sits below it in the process tree) /T would kill the panel
    //    along with the target - the stop button would take the panel down too.
    let pids = pids_on_port(port);
    if pids.is_empty() {
        return ActionResult {
            ok: false,
            action: "stop".into(),
            message: format!("端口 {port} 上没有在监听的进程"),
            output: String::new(),
        };
    }

    let me = std::process::id();
    let mut killed: Vec<u32> = Vec::new();
    let mut refused: Vec<u32> = Vec::new();
    for pid in pids {
        if pid == me {
            refused.push(pid);
            continue;
        }
        let is_node = process_name(pid)
            .map(|n| n.eq_ignore_ascii_case("node.exe"))
            .unwrap_or(false);
        if !is_node {
            refused.push(pid);
            continue;
        }
        let ok = Command::new("cmd")
            .args(["/c", "taskkill", "/PID", &pid.to_string(), "/F"])
            .creation_flags(CREATE_NO_WINDOW)
            .output()
            .map(|o| o.status.success())
            .unwrap_or(false);
        if ok {
            killed.push(pid);
        } else {
            refused.push(pid);
        }
    }

    let join = |v: &[u32]| v.iter().map(|p| p.to_string()).collect::<Vec<_>>().join(", ");
    ActionResult {
        ok: !killed.is_empty(),
        action: "stop".into(),
        message: if !killed.is_empty() {
            format!("已停止占用端口 {port} 的 harness（PID {}）", join(&killed))
        } else {
            format!("端口 {port} 被非 node 进程占用（PID {}），没有动它", join(&refused))
        },
        output: String::new(),
    }
}

/// Whether the desktop app the panel launched is still alive.
#[tauri::command]
fn desktop_running() -> bool {
    match DESKTOP_CHILD
        .get_or_init(|| Mutex::new(None))
        .lock()
        .unwrap()
        .as_mut()
    {
        Some(child) => matches!(child.try_wait(), Ok(None)),
        None => false,
    }
}

#[tauri::command]
fn get_settings(app: AppHandle) -> Settings {
    load_settings(&app)
}

/// Save (or clear) the source checkout the desktop app is launched from.
#[tauri::command]
fn set_desktop_source_dir(app: AppHandle, dir: Option<String>) -> ActionResult {
    let mut settings = load_settings(&app);
    settings.desktop_source_dir = dir
        .map(|d| d.trim().to_string())
        .filter(|d| !d.is_empty());
    save_settings(&app, &settings);

    ActionResult {
        ok: true,
        action: "settings".into(),
        message: match &settings.desktop_source_dir {
            Some(d) => format!("已保存源码目录：{d}"),
            None => "已清除源码目录".into(),
        },
        output: String::new(),
    }
}

/// Launch the Electron desktop app FROM SOURCE. `dev:desktop` builds the host,
/// client bundles, web frontend and Electron shell first, so the first run is slow.
#[tauri::command]
async fn start_desktop_app(app: AppHandle) -> ActionResult {
    let Some(dir) = load_settings(&app).desktop_source_dir else {
        return ActionResult {
            ok: false,
            action: "desktop".into(),
            message: "还没配置源码目录，先在下面的「桌面端源码目录」里选一个".into(),
            output: String::new(),
        };
    };

    if let Some(problem) = source_dir_problem(&dir) {
        return ActionResult {
            ok: false,
            action: "desktop".into(),
            message: problem,
            output: String::new(),
        };
    }

    let root = PathBuf::from(&dir);
    let _ = app.emit("harness-output", format!("$ cd {dir}"));
    let _ = app.emit("harness-output", "$ pnpm run dev:desktop");

    let mut child = match Command::new("cmd")
        .args(["/c", "pnpm", "run", "dev:desktop"])
        .current_dir(&root)
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .creation_flags(CREATE_NO_WINDOW)
        .spawn()
    {
        Ok(c) => c,
        Err(e) => {
            return ActionResult {
                ok: false,
                action: "desktop".into(),
                message: format!("启动失败: {e}"),
                output: String::new(),
            }
        }
    };

    pipe_to_terminal(&app, &mut child);
    *DESKTOP_CHILD.get_or_init(|| Mutex::new(None)).lock().unwrap() = Some(child);

    ActionResult {
        ok: true,
        action: "desktop".into(),
        message: "已在面板内启动 Electron 桌面端（首次会构建，需要几分钟）".into(),
        output: String::new(),
    }
}

#[tauri::command]
fn stop_desktop_app() -> ActionResult {
    let stopped = DESKTOP_CHILD
        .get_or_init(|| Mutex::new(None))
        .lock()
        .unwrap()
        .take()
        .map(|mut c| {
            let _ = c.kill();
            let _ = c.wait();
            true
        })
        .unwrap_or(false);

    ActionResult {
        ok: stopped,
        action: "stop".into(),
        message: if stopped {
            "已停止面板启动的桌面端".into()
        } else {
            "没有由面板启动的桌面端".into()
        },
        output: String::new(),
    }
}

/// Lets the panel render the harness state immediately instead of waiting for
/// the next poll tick.
#[tauri::command]
fn harness_running() -> bool {
    HARNESS_RUNNING.load(Ordering::Relaxed)
}

#[tauri::command]
fn quit_app(app: AppHandle) {
    app.exit(0);
}

// ---------------------------------------------------------------------------
// Bootstrap
// ---------------------------------------------------------------------------

/// True when this process belongs to a Windows Job Object.
#[cfg(windows)]
fn in_any_job() -> bool {
    #[link(name = "kernel32")]
    extern "system" {
        fn GetCurrentProcess() -> *mut core::ffi::c_void;
        fn IsProcessInJob(
            process: *mut core::ffi::c_void,
            job: *mut core::ffi::c_void,
            result: *mut i32,
        ) -> i32;
    }
    let mut result: i32 = 0;
    // A null job handle asks "is it in ANY job?".
    let ok = unsafe { IsProcessInJob(GetCurrentProcess(), std::ptr::null_mut(), &mut result) };
    ok != 0 && result != 0
}

#[cfg(not(windows))]
fn in_any_job() -> bool {
    false
}

/// The harness runs its children inside a Windows Job Object, so a panel started
/// from a harness session dies together with the harness - no `taskkill` flag can
/// prevent that, because closing the job terminates every member process.
///
/// So: if we find ourselves inside any job, relaunch through explorer.exe (which
/// is not in that job) and let this instance exit. The env marker keeps it to one
/// hop, so a genuinely orphaned panel does not loop forever.
#[cfg(windows)]
fn detach_from_job_if_needed() {
    if std::env::var_os("DSH_PANEL_DETACHED").is_some() || !in_any_job() {
        return;
    }
    let Ok(exe) = std::env::current_exe() else {
        return;
    };
    let spawned = std::process::Command::new("explorer.exe")
        .arg(&exe)
        .env("DSH_PANEL_DETACHED", "1")
        .spawn()
        .is_ok();
    if spawned {
        std::process::exit(0);
    }
}

#[cfg(not(windows))]
fn detach_from_job_if_needed() {}

// ---------------------------------------------------------------------------
// Provider balance
//
// Queried directly against the provider, with the key read from the harness
// credential store. The usage plugin used to answer this; it is gone, and the
// panel must not depend on plugins for features it needs.
// ---------------------------------------------------------------------------

#[derive(Serialize, Clone)]
struct BalanceInfo {
    ok: bool,
    provider: String,
    currency: String,
    total: String,
    topped_up: String,
    granted: String,
    queried_at: u64,
    error: Option<String>,
}


// ---------------------------------------------------------------------------
// Plugin management (thin wrapper over `dsh plugin --profile X ...`, i.e. pnpm)
// ---------------------------------------------------------------------------

#[derive(Serialize, Clone)]
struct PluginInfo {
    /// Package name, e.g. @feiyang666/dsh-usage-plugin
    name: String,
    /// Version actually installed in the profile's node_modules ("" if missing)
    installed: String,
    /// Version range recorded in the profile's package.json
    spec: String,
}

#[derive(Serialize, Clone)]
struct ProfilePlugins {
    profile: String,
    /// Bundles the profile loads (official ones included).
    bundles: Vec<String>,
    /// Third-party packages this profile depends on.
    plugins: Vec<PluginInfo>,
    error: Option<String>,
}

fn profiles_root(app: &AppHandle) -> Option<PathBuf> {
    // %USERPROFILE%\.dsh\profiles
    let home = app.path().home_dir().ok()?;
    Some(home.join(".dsh").join("profiles"))
}

/// Read the version a package resolved to inside one profile.
fn installed_version(profile_dir: &PathBuf, name: &str) -> String {
    let pkg = profile_dir
        .join("node_modules")
        .join(name)
        .join("package.json");
    std::fs::read_to_string(pkg)
        .ok()
        .and_then(|t| serde_json::from_str::<serde_json::Value>(&t).ok())
        .and_then(|v| v.get("version").and_then(|x| x.as_str()).map(String::from))
        .unwrap_or_default()
}

#[tauri::command]
fn list_plugins(app: AppHandle) -> Vec<ProfilePlugins> {
    let Some(root) = profiles_root(&app) else {
        return Vec::new();
    };
    let Ok(entries) = std::fs::read_dir(&root) else {
        return Vec::new();
    };

    let mut out = Vec::new();
    let mut dirs: Vec<PathBuf> = entries
        .filter_map(|e| e.ok().map(|e| e.path()))
        .filter(|p| p.is_dir())
        .collect();
    dirs.sort();

    for dir in dirs {
        let name = match dir.file_name().and_then(|n| n.to_str()) {
            Some(n) => n.to_string(),
            None => continue,
        };
        // `node_modules` is the pnpm store link, not a profile.
        if name == "node_modules" {
            continue;
        }
        let manifest = dir.join("package.json");
        if !manifest.is_file() {
            continue;
        }
        let parsed = std::fs::read_to_string(&manifest)
            .ok()
            .and_then(|t| serde_json::from_str::<serde_json::Value>(&t).ok());

        let Some(v) = parsed else {
            out.push(ProfilePlugins {
                profile: name,
                bundles: Vec::new(),
                plugins: Vec::new(),
                error: Some("package.json 解析失败".into()),
            });
            continue;
        };

        let bundles: Vec<String> = v["dsh"]["profile"]["bundles"]
            .as_array()
            .map(|a| a.iter().filter_map(|x| x.as_str().map(String::from)).collect())
            .unwrap_or_default();

        let mut plugins = Vec::new();
        if let Some(deps) = v["dependencies"].as_object() {
            for (dep, spec) in deps {
                plugins.push(PluginInfo {
                    name: dep.clone(),
                    installed: installed_version(&dir, dep),
                    spec: spec.as_str().unwrap_or("").to_string(),
                });
            }
        }
        plugins.sort_by(|a, b| a.name.cmp(&b.name));

        out.push(ProfilePlugins {
            profile: name,
            bundles,
            plugins,
            error: None,
        });
    }
    out
}

/// Run `dsh plugin --profile <p> <args...>` and stream its output to the terminal.
fn run_dsh_plugin(app: &AppHandle, profile: String, args: Vec<String>) -> ActionResult {
    let mut cmd = Command::new("cmd");
    cmd.arg("/c").arg("dsh").arg("plugin").arg("--profile").arg(&profile);
    for a in &args {
        cmd.arg(a);
    }
    cmd.stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .creation_flags(CREATE_NO_WINDOW);

    let _ = app.emit("harness-output", format!("$ dsh plugin --profile {profile} {}", args.join(" ")));

    match cmd.spawn() {
        Ok(mut child) => {
            pipe_to_terminal(app, &mut child);
            *PLUGIN_CHILD.get_or_init(|| Mutex::new(None)).lock().unwrap() = Some(child);
            ActionResult {
                ok: true,
                action: "plugin".into(),
                message: format!("已开始执行（输出见终端）；装/卸插件后需要重启 Web 端才生效"),
                output: String::new(),
            }
        }
        Err(e) => ActionResult {
            ok: false,
            action: "plugin".into(),
            message: format!("无法执行 dsh: {e}"),
            output: String::new(),
        },
    }
}

#[tauri::command]
async fn install_plugin(app: AppHandle, profile: String, package: String) -> ActionResult {
    let package = package.trim().to_string();
    if package.is_empty() {
        return ActionResult {
            ok: false,
            action: "plugin".into(),
            message: "请填写包名，例如 @scope/dsh-xxx".into(),
            output: String::new(),
        };
    }
    run_dsh_plugin(&app, profile, vec!["add".into(), package])
}

#[tauri::command]
async fn remove_plugin(app: AppHandle, profile: String, package: String) -> ActionResult {
    run_dsh_plugin(&app, profile, vec!["remove".into(), package])
}

#[tauri::command]
async fn upgrade_plugins(app: AppHandle, profile: String) -> ActionResult {
    run_dsh_plugin(&app, profile, vec!["update".into()])
}

#[tauri::command]
fn plugin_op_running() -> bool {
    match PLUGIN_CHILD
        .get_or_init(|| Mutex::new(None))
        .lock()
        .unwrap()
        .as_mut()
    {
        Some(child) => matches!(child.try_wait(), Ok(None)),
        None => false,
    }
}

// ---------------------------------------------------------------------------
// Feishu → dsh bridge
// ---------------------------------------------------------------------------

/// The bridge script, embedded so the installed exe does not need the repo.
const BRIDGE_JS: &str = include_str!("../../scripts/feishu-bridge.mjs");

static BRIDGE_CHILD: OnceLock<Mutex<Option<std::process::Child>>> = OnceLock::new();

#[derive(Serialize, Clone)]
struct BridgeStatus {
    running: bool,
    /// Absolute path of the extracted helper script.
    script: String,
}

/// Write the embedded bridge next to our app data and return its path.
fn bridge_script_path(app: &AppHandle) -> Result<PathBuf, String> {
    let dir = app
        .path()
        .app_data_dir()
        .map_err(|e| format!("取不到应用数据目录: {e}"))?;
    std::fs::create_dir_all(&dir).map_err(|e| format!("创建应用数据目录失败: {e}"))?;
    let path = dir.join("feishu-bridge.mjs");
    // Always refresh: the script is versioned with the exe.
    std::fs::write(&path, BRIDGE_JS).map_err(|e| format!("写入桥脚本失败: {e}"))?;
    Ok(path)
}

fn bridge_running_inner() -> bool {
    match BRIDGE_CHILD
        .get_or_init(|| Mutex::new(None))
        .lock()
        .unwrap()
        .as_mut()
    {
        Some(child) => matches!(child.try_wait(), Ok(None)),
        None => false,
    }
}

#[tauri::command]
fn feishu_bridge_status(app: AppHandle) -> BridgeStatus {
    let script = bridge_script_path(&app)
        .map(|p| p.to_string_lossy().to_string())
        .unwrap_or_default();
    BridgeStatus {
        running: bridge_running_inner(),
        script,
    }
}

/// Start the bridge. `allowed_users` is required: without it the bridge refuses
/// every message, because a Feishu bot message is effectively shell access here.
#[tauri::command]
fn feishu_bridge_start(
    app: AppHandle,
    allowed_users: String,
    profile: Option<String>,
) -> ActionResult {
    if bridge_running_inner() {
        return ActionResult {
            ok: false,
            action: "feishu".into(),
            message: "桥已经在运行".into(),
            output: String::new(),
        };
    }
    let allowed = allowed_users.trim().to_string();
    if allowed.is_empty() {
        return ActionResult {
            ok: false,
            action: "feishu".into(),
            message: "请先填白名单 open_id（ou_ 开头）。留空等于对所有人开放本机执行权限，所以不允许启动。".into(),
            output: String::new(),
        };
    }

    let script = match bridge_script_path(&app) {
        Ok(p) => p,
        Err(e) => {
            return ActionResult {
                ok: false,
                action: "feishu".into(),
                message: e,
                output: String::new(),
            }
        }
    };
    let profile = profile.unwrap_or_else(|| "headless".into());

    let _ = app.emit("harness-output", "$ feishu-bridge （飞书 → dsh）".to_string());

    match Command::new("cmd")
        .arg("/c")
        .arg("node")
        .arg(&script)
        .env("FEISHU_ALLOWED_USERS", &allowed)
        .env("DSH_BRIDGE_PROFILE", &profile)
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .creation_flags(CREATE_NO_WINDOW)
        .spawn()
    {
        Ok(mut child) => {
            pipe_to_terminal(&app, &mut child);
            *BRIDGE_CHILD.get_or_init(|| Mutex::new(None)).lock().unwrap() = Some(child);
            ActionResult {
                ok: true,
                action: "feishu".into(),
                message: format!("桥已启动（profile={profile}，白名单 {allowed}）"),
                output: String::new(),
            }
        }
        Err(e) => ActionResult {
            ok: false,
            action: "feishu".into(),
            message: format!("启动失败: {e}"),
            output: String::new(),
        },
    }
}

#[tauri::command]
fn feishu_bridge_stop() -> ActionResult {
    let taken = BRIDGE_CHILD
        .get_or_init(|| Mutex::new(None))
        .lock()
        .unwrap()
        .take();
    match taken {
        Some(mut child) => {
            let pid = child.id();
            // Kill the tree: we launch through cmd, so the node process is a child.
            let _ = Command::new("cmd")
                .args(["/c", "taskkill", "/PID", &pid.to_string(), "/F", "/T"])
                .creation_flags(CREATE_NO_WINDOW)
                .output();
            let _ = child.wait();
            ActionResult {
                ok: true,
                action: "feishu".into(),
                message: "桥已停止".into(),
                output: String::new(),
            }
        }
        None => ActionResult {
            ok: false,
            action: "feishu".into(),
            message: "桥没有在运行".into(),
            output: String::new(),
        },
    }
}

/// Open the harness web UI in the default browser. Pure navigation - never
/// starts anything, so it is safe to press even when the state is unknown.
#[tauri::command]
fn open_harness_page(port: Option<u16>) -> ActionResult {
    let port = port.unwrap_or(DEFAULT_HARNESS_PORT);
    let url = harness_url(port);
    // `start` treats the first quoted argument as a window title, hence the "".
    match Command::new("cmd")
        .args(["/c", "start", "", &url])
        .creation_flags(CREATE_NO_WINDOW)
        .spawn()
    {
        Ok(_) => ActionResult {
            ok: true,
            action: "browser".into(),
            message: format!("已在浏览器打开 {url}"),
            output: String::new(),
        },
        Err(e) => ActionResult {
            ok: false,
            action: "browser".into(),
            message: format!("打开浏览器失败: {e}"),
            output: String::new(),
        },
    }
}

// ---------------------------------------------------------------------------
// Hermes gateway (read-only status)
// ---------------------------------------------------------------------------

/// Host path of the Hermes gateway state file (the docker volume
/// `docker/hermes/data` mounted at `/opt/data` inside the container).
const HERMES_STATE_FILE: &str = r"C:\workspace\docker\hermes\data\gateway_state.json";
const HERMES_DASHBOARD_PORT: u16 = 9119;

#[derive(Serialize, Clone)]
struct HermesPlatform {
    name: String,
    state: String,
    needs_attention: bool,
}

#[derive(Serialize, Clone)]
struct HermesStatus {
    ok: bool,
    gateway_state: String,
    code_version: String,
    active_agents: u64,
    pid: u64,
    platforms: Vec<HermesPlatform>,
    /// File the reading came from (empty if we could not read it).
    source: String,
    error: Option<String>,
}

/// Read (never write) the gateway state so the panel can show whether the
/// Hermes bridge is up and which platforms are connected.
#[tauri::command]
fn hermes_status() -> HermesStatus {
    let fail = |err: String| HermesStatus {
        ok: false,
        gateway_state: String::new(),
        code_version: String::new(),
        active_agents: 0,
        pid: 0,
        platforms: Vec::new(),
        source: String::new(),
        error: Some(err),
    };

    let text = match std::fs::read_to_string(HERMES_STATE_FILE) {
        Ok(t) => t,
        Err(e) => return fail(format!("读不到 Hermes 状态文件: {e}")),
    };
    let v: serde_json::Value = match serde_json::from_str(&text) {
        Ok(v) => v,
        Err(e) => return fail(format!("解析 Hermes 状态失败: {e}")),
    };

    let mut platforms = Vec::new();
    if let Some(map) = v["platforms"].as_object() {
        for (name, p) in map {
            platforms.push(HermesPlatform {
                name: name.clone(),
                state: p["state"].as_str().unwrap_or("unknown").to_string(),
                needs_attention: p["needs_attention"].as_bool().unwrap_or(false),
            });
        }
        platforms.sort_by(|a, b| a.name.cmp(&b.name));
    }

    HermesStatus {
        ok: true,
        gateway_state: v["gateway_state"].as_str().unwrap_or("unknown").to_string(),
        code_version: v["code_version"].as_str().unwrap_or("").to_string(),
        active_agents: v["active_agents"].as_u64().unwrap_or(0),
        pid: v["pid"].as_u64().unwrap_or(0),
        platforms,
        source: HERMES_STATE_FILE.to_string(),
        error: None,
    }
}

/// Open the Hermes dashboard in the browser.
#[tauri::command]
fn open_hermes_page() -> ActionResult {
    let url = format!("http://127.0.0.1:{HERMES_DASHBOARD_PORT}");
    match Command::new("cmd")
        .args(["/c", "start", "", &url])
        .creation_flags(CREATE_NO_WINDOW)
        .spawn()
    {
        Ok(_) => ActionResult {
            ok: true,
            action: "browser".into(),
            message: format!("已在浏览器打开 {url}"),
            output: String::new(),
        },
        Err(e) => ActionResult {
            ok: false,
            action: "browser".into(),
            message: format!("打开浏览器失败: {e}"),
            output: String::new(),
        },
    }
}

// ---------------------------------------------------------------------------
// Usage store
//
// Token accounting is the harness kernel's own feature (packages/llm/token-meter):
// it derives exact per-turn usage from session events. Plugins that show charts
// merely parse those sessions and cache the result. Since this panel must keep
// working after plugins are uninstalled, it keeps its own store here:
//   %APPDATA%\<identifier>\usage\YYYY-MM-DD.json   (one aggregated file per day)
// ---------------------------------------------------------------------------

/// One aggregate over the same five token buckets. Used at day level, per model
/// and per session, so every view shares one arithmetic.
#[derive(Serialize, Deserialize, Clone, Default)]
struct Bucket {
    calls: u64,
    /// Prompt tokens that were *not* served from cache.
    input_tokens: u64,
    output_tokens: u64,
    cache_read_tokens: u64,
    cache_write_tokens: u64,
    reasoning_tokens: u64,
    cost: f64,
    /// DeepSeek bills peak and off-peak hours at different rates.
    peak_cost: f64,
    offpeak_cost: f64,
    peak_calls: u64,
}

impl Bucket {
    /// Total tokens processed: prompt (cache-miss + cache-hit) plus completion.
    ///
    /// `cache_write_tokens` is deliberately excluded: the recorder sets it equal
    /// to the miss count (a miss is what gets written to cache), so adding it
    /// would double-count the prompt. The plugin's own `tokens` figure does
    /// exactly that, which is why its totals look inflated.
    fn tokens(&self) -> u64 {
        self.input_tokens + self.cache_read_tokens + self.output_tokens
    }

    /// Prompt tokens seen, cached or not.
    fn prompt_tokens(&self) -> u64 {
        self.input_tokens + self.cache_read_tokens
    }

    /// Cache hit rate as a percentage (0 when no prompt tokens were seen).
    fn cache_hit_pct(&self) -> f64 {
        let prompt = self.prompt_tokens();
        if prompt == 0 {
            return 0.0;
        }
        (self.cache_read_tokens as f64 / prompt as f64) * 100.0
    }

    #[allow(clippy::too_many_arguments)]
    fn add(
        &mut self,
        input: u64,
        output: u64,
        cache_read: u64,
        cache_write: u64,
        reasoning: u64,
        cost: f64,
        peak: bool,
    ) {
        self.calls += 1;
        self.input_tokens += input;
        self.output_tokens += output;
        self.cache_read_tokens += cache_read;
        self.cache_write_tokens += cache_write;
        self.reasoning_tokens += reasoning;
        self.cost += cost;
        if peak {
            self.peak_cost += cost;
            self.peak_calls += 1;
        } else {
            self.offpeak_cost += cost;
        }
    }

    fn merge(&mut self, other: &Bucket) {
        self.calls += other.calls;
        self.input_tokens += other.input_tokens;
        self.output_tokens += other.output_tokens;
        self.cache_read_tokens += other.cache_read_tokens;
        self.cache_write_tokens += other.cache_write_tokens;
        self.reasoning_tokens += other.reasoning_tokens;
        self.cost += other.cost;
        self.peak_cost += other.peak_cost;
        self.offpeak_cost += other.offpeak_cost;
        self.peak_calls += other.peak_calls;
    }
}

#[derive(Serialize, Deserialize, Clone, Default)]
struct DayUsage {
    date: String,
    #[serde(flatten)]
    total: Bucket,
    by_model: HashMap<String, Bucket>,
    /// Session id -> usage. Feeds the "top sessions" ranking.
    #[serde(default)]
    by_session: HashMap<String, Bucket>,
}

fn usage_dir(app: &AppHandle) -> Result<PathBuf, String> {
    let dir = app
        .path()
        .app_data_dir()
        .map_err(|e| format!("取不到应用数据目录: {e}"))?
        .join("usage");
    std::fs::create_dir_all(&dir).map_err(|e| format!("创建用量目录失败: {e}"))?;
    Ok(dir)
}

/// Local (not UTC) calendar date for a millisecond timestamp.
fn local_date(ms: i64) -> String {
    chrono::DateTime::from_timestamp_millis(ms)
        .map(|dt| {
            dt.with_timezone(&chrono::Local)
                .format("%Y-%m-%d")
                .to_string()
        })
        .unwrap_or_else(|| "1970-01-01".to_string())
}

fn load_day(path: &PathBuf, date: &str) -> DayUsage {
    let mut day = std::fs::read_to_string(path)
        .ok()
        .and_then(|t| serde_json::from_str::<DayUsage>(&t).ok())
        .unwrap_or_default();
    day.date = date.to_string();
    day
}

fn save_day(dir: &PathBuf, day: &DayUsage) -> Result<(), String> {
    let path = dir.join(format!("{}.json", day.date));
    let text = serde_json::to_string(day).map_err(|e| e.to_string())?;
    std::fs::write(path, text).map_err(|e| e.to_string())
}

/// Every day file we hold, sorted by date ascending.
fn load_all_days(app: &AppHandle) -> Result<Vec<DayUsage>, String> {
    let dir = usage_dir(app)?;
    let mut days = Vec::new();
    for entry in std::fs::read_dir(&dir).map_err(|e| e.to_string())? {
        let Ok(entry) = entry else { continue };
        let path = entry.path();
        if path.extension().and_then(|e| e.to_str()) != Some("json") {
            continue;
        }
        let Some(stem) = path.file_stem().and_then(|s| s.to_str()) else {
            continue;
        };
        // Only YYYY-MM-DD.json counts.
        if stem.len() != 10 {
            continue;
        }
        days.push(load_day(&path, stem));
    }
    days.sort_by(|a, b| a.date.cmp(&b.date));
    Ok(days)
}

/// One point on a chart.
#[derive(Serialize, Clone)]
struct UsagePoint {
    /// Axis label: "09-18" (day) · "09-08周" (week) · "2026-09" (month)
    label: String,
    /// ISO week / month key, so the UI can show a tooltip title.
    key: String,
    cost: f64,
    tokens: u64,
    calls: u64,
}

#[derive(Serialize, Clone)]
struct UsageSeries {
    ok: bool,
    bucket: String,
    points: Vec<UsagePoint>,
    total_cost: f64,
    total_tokens: u64,
    total_calls: u64,
    /// Current local calendar month, independent of the selected bucket.
    month_cost: f64,
    month_tokens: u64,
    month_calls: u64,
    /// How many of the requested buckets actually had data (the rest are gaps).
    filled: u32,
    error: Option<String>,
}


/// Aggregate the store into day / week / month buckets.
#[tauri::command]
fn usage_series(app: AppHandle, bucket: Option<String>, count: Option<u32>) -> UsageSeries {
    let bucket = bucket.unwrap_or_else(|| "day".into());
    let default_count = match bucket.as_str() {
        "week" => 8,
        "month" => 12,
        _ => 14,
    };
    let count = count.unwrap_or(default_count).clamp(1, 60);

    let fail = |err: String| UsageSeries {
        ok: false,
        bucket: bucket.clone(),
        points: Vec::new(),
        total_cost: 0.0,
        total_tokens: 0,
        total_calls: 0,
        month_cost: 0.0,
        month_tokens: 0,
        month_calls: 0,
        filled: 0,
        error: Some(err),
    };

    let days = match load_all_days(&app) {
        Ok(d) => d,
        Err(e) => return fail(e),
    };

    let today = chrono::Local::now().date_naive();
    let month_prefix = today.format("%Y-%m").to_string();

    // Current calendar month totals, always computed regardless of bucket.
    let mut month_cost = 0.0;
    let mut month_tokens = 0u64;
    let mut month_calls = 0u64;
    for d in &days {
        if d.date.starts_with(&month_prefix) {
            month_cost += d.total.cost;
            month_tokens += d.total.tokens();
            month_calls += d.total.calls;
        }
    }

    // Bucket key + label for one day, plus the ordered list of buckets we want.
    let key_of = |date: &chrono::NaiveDate| -> String {
        match bucket.as_str() {
            "week" => date.format("%G-W%V").to_string(),
            "month" => date.format("%Y-%m").to_string(),
            _ => date.format("%Y-%m-%d").to_string(),
        }
    };

    let mut wanted: Vec<String> = Vec::new();
    match bucket.as_str() {
        "week" => {
            // Count back whole weeks from the current ISO week.
            let mut cursor = today;
            for _ in 0..count {
                wanted.push(key_of(&cursor));
                cursor -= chrono::Duration::days(7);
            }
        }
        "month" => {
            let mut year = today.year();
            let mut month = today.month();
            for _ in 0..count {
                wanted.push(format!("{year:04}-{month:02}"));
                if month == 1 {
                    month = 12;
                    year -= 1;
                } else {
                    month -= 1;
                }
            }
        }
        _ => {
            let mut cursor = today;
            for _ in 0..count {
                wanted.push(cursor.format("%Y-%m-%d").to_string());
                cursor -= chrono::Duration::days(1);
            }
        }
    }
    wanted.reverse(); // oldest -> newest

    // Fold the store into those buckets.
    let mut acc: HashMap<String, (f64, u64, u64)> = HashMap::new();
    let horizon = wanted.first().cloned().unwrap_or_default();
    for d in &days {
        let key = d.date.clone();
        // Only keep days that can land in a wanted bucket.
        let in_range = match bucket.as_str() {
            "month" => key.as_str() >= horizon.as_str(),
            _ => true,
        };
        if !in_range {
            continue;
        }
        let bucket_key = match bucket.as_str() {
            "week" | "month" => match chrono::NaiveDate::parse_from_str(&key, "%Y-%m-%d") {
                Ok(date) => key_of(&date),
                Err(_) => continue,
            },
            _ => key,
        };
        if !wanted.contains(&bucket_key) {
            continue;
        }
        let slot = acc.entry(bucket_key).or_insert((0.0, 0, 0));
        slot.0 += d.total.cost;
        slot.1 += d.total.tokens();
        slot.2 += d.total.calls;
    }

    let mut points = Vec::new();
    let mut filled = 0u32;
    for key in &wanted {
        let (cost, tokens, calls) = acc.get(key).copied().unwrap_or((0.0, 0, 0));
        if calls > 0 {
            filled += 1;
        }
        let label = match bucket.as_str() {
            "week" => key
                .split("-W")
                .nth(1)
                .map(|w| format!("第{w}周"))
                .unwrap_or_else(|| key.clone()),
            "month" => key
                .split('-')
                .nth(1)
                .map(|m| format!("{m}月"))
                .unwrap_or_else(|| key.clone()),
            _ => key.get(5..).unwrap_or(key).to_string(),
        };
        points.push(UsagePoint {
            label,
            key: key.clone(),
            cost,
            tokens,
            calls,
        });
    }

    let total_cost = points.iter().map(|p| p.cost).sum();
    let total_tokens = points.iter().map(|p| p.tokens).sum();
    let total_calls = points.iter().map(|p| p.calls).sum();

    UsageSeries {
        ok: true,
        bucket,
        points,
        total_cost,
        total_tokens,
        total_calls,
        month_cost,
        month_tokens,
        month_calls,
        filled,
        error: None,
    }
}

/// Read one secret out of the harness credential store (`~/.dsh/.credentials.yaml`).
///
/// Only `refs.<NAME>` is needed, so this scans lines instead of pulling in a YAML
/// parser: it keeps unrelated secrets off the heap entirely, and the file is a
/// flat `refs:` block in every version we have seen.
fn read_dsh_credential(name: &str) -> Option<String> {
    let home = std::env::var("USERPROFILE").ok()?;
    let path = PathBuf::from(home).join(".dsh").join(".credentials.yaml");
    let text = std::fs::read_to_string(path).ok()?;

    let mut in_refs = false;
    let prefix = format!("{name}:");
    for line in text.lines() {
        if !in_refs {
            if line.trim_start().starts_with("refs:") && !line.starts_with(' ') {
                in_refs = true;
            }
            continue;
        }
        // A non-indented, non-empty line ends the refs block.
        if !line.trim().is_empty() && !line.starts_with(' ') && !line.starts_with('\t') {
            break;
        }
        let trimmed = line.trim();
        if let Some(rest) = trimmed.strip_prefix(&prefix) {
            let value = rest.trim().trim_matches(|c| c == '"' || c == '\'');
            if !value.is_empty() && !value.starts_with('<') {
                return Some(value.to_string());
            }
        }
    }
    None
}

/// Query the provider balance ourselves.
///
/// The plugin used to do this, but the whole point of the panel owning its own
/// data is that uninstalling plugins must not remove working features.
#[tauri::command]
async fn get_balance_native(provider: Option<String>) -> BalanceInfo {
    let provider = provider.unwrap_or_else(|| "deepseek".into());
    let fail = |err: String| BalanceInfo {
        ok: false,
        provider: provider.clone(),
        currency: String::new(),
        total: String::new(),
        topped_up: String::new(),
        granted: String::new(),
        queried_at: 0,
        error: Some(err),
    };

    let Some(key) = read_dsh_credential("DEEPSEEK_API_KEY") else {
        return fail("在 ~/.dsh/.credentials.yaml 的 refs 里找不到 DEEPSEEK_API_KEY".into());
    };

    let client = match reqwest::Client::builder()
        .timeout(Duration::from_secs(20))
        .build()
    {
        Ok(c) => c,
        Err(e) => return fail(format!("创建 HTTP 客户端失败: {e}")),
    };

    let resp = match client
        .get("https://api.deepseek.com/user/balance")
        .bearer_auth(&key)
        .header("Accept", "application/json")
        .send()
        .await
    {
        Ok(r) => r,
        Err(e) => return fail(format!("请求 DeepSeek 余额接口失败: {e}")),
    };

    if !resp.status().is_success() {
        let status = resp.status();
        return fail(match status.as_u16() {
            401 => "DeepSeek 返回 401：API Key 无效或已撤销".to_string(),
            402 => "DeepSeek 返回 402：账户余额不足".to_string(),
            _ => format!("DeepSeek 返回 HTTP {status}"),
        });
    }

    let value: serde_json::Value = match resp.json().await {
        Ok(v) => v,
        Err(e) => return fail(format!("解析余额响应失败: {e}")),
    };

    let info = &value["balance_infos"][0];
    let total = info["total_balance"].as_str().unwrap_or("").to_string();
    if total.is_empty() {
        return fail("余额响应里没有 total_balance".into());
    }

    BalanceInfo {
        ok: true,
        provider,
        currency: info["currency"].as_str().unwrap_or("CNY").to_string(),
        total,
        topped_up: info["topped_up_balance"].as_str().unwrap_or("").to_string(),
        granted: info["granted_balance"].as_str().unwrap_or("").to_string(),
        queried_at: now_secs(),
        error: None,
    }
}

// ---------------------------------------------------------------------------
// Session scanner
//
// The kernel (packages/llm/token-meter) derives exact per-turn token usage from
// session events, but never writes a separate usage file: the only durable
// record is the session log itself. Session logs are *multi-frame* zstd
// (one frame appended per write; the file we inspected held 1174 frames), so a
// single-shot decompressor fails on them - `zstd::stream::read::Decoder` walks
// frame boundaries itself.
// ---------------------------------------------------------------------------

fn sessions_root() -> Option<PathBuf> {
    let home = std::env::var("USERPROFILE").ok()?;
    let dir = PathBuf::from(home).join(".dsh").join("sessions");
    if dir.is_dir() {
        Some(dir)
    } else {
        None
    }
}

/// Every session log under the root (order unspecified; callers sort).
fn session_files(root: &PathBuf) -> Vec<PathBuf> {
    let mut out = Vec::new();
    let mut stack = vec![root.clone()];
    while let Some(dir) = stack.pop() {
        let Ok(entries) = std::fs::read_dir(&dir) else {
            continue;
        };
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() {
                stack.push(path);
            } else if path
                .file_name()
                .and_then(|n| n.to_str())
                .map(|n| n.ends_with(".jsonl.zstd"))
                .unwrap_or(false)
            {
                out.push(path);
            }
        }
    }
    out
}

/// Decompress a multi-frame zstd session log into its JSONL lines.
fn read_session_lines(path: &PathBuf) -> Result<Vec<String>, String> {
    use std::io::Read;
    let file = std::fs::File::open(path).map_err(|e| format!("打开失败: {e}"))?;
    let mut decoder =
        zstd::stream::read::Decoder::new(file).map_err(|e| format!("zstd 初始化失败: {e}"))?;
    let mut text = String::new();
    decoder
        .read_to_string(&mut text)
        .map_err(|e| format!("解压失败: {e}"))?;
    Ok(text.lines().map(|l| l.to_string()).collect())
}

/// Diagnostic pass: report what event types actually appear in the logs, so the
/// aggregation is written against the real structure rather than a guess.
#[tauri::command]
fn scan_sessions_diag(limit: Option<usize>) -> ActionResult {
    let Some(root) = sessions_root() else {
        return ActionResult {
            ok: false,
            action: "scan".into(),
            message: "找不到 ~/.dsh/sessions".into(),
            output: String::new(),
        };
    };
    let mut files = session_files(&root);
    files.sort();
    let limit = limit.unwrap_or(3);

    let mut by_type: HashMap<String, usize> = HashMap::new();
    let mut samples: Vec<String> = Vec::new();
    let mut usage_samples: Vec<String> = Vec::new();
    let mut events = 0usize;
    let mut total_lines = 0usize;
    let mut errors: Vec<String> = Vec::new();

    for path in files.iter().take(limit) {
        match read_session_lines(path) {
            Ok(lines) => {
                total_lines += lines.len();
                for line in lines {
                    let trimmed = line.trim();
                    if trimmed.is_empty() {
                        continue;
                    }
                    events += 1;
                    let Ok(v) = serde_json::from_str::<serde_json::Value>(trimmed) else {
                        continue;
                    };
                    let ty = v["type"].as_str().unwrap_or("<no type>").to_string();
                    *by_type.entry(ty.clone()).or_insert(0) += 1;

                    // Keep several raw usage objects: the first one may lack
                    // optional buckets, which hides the real accounting.
                    if ty == "assistant/message" && usage_samples.len() < 8 {
                        let usage = &v["data"]["usage"];
                        if !usage.is_null() {
                            usage_samples.push(format!(
                                "usage[{}] {}",
                                usage_samples.len(),
                                serde_json::to_string(usage).unwrap_or_default()
                            ));
                        } else {
                            usage_samples.push(format!(
                                "usage[{}] <null> keys={}",
                                usage_samples.len(),
                                v["data"]
                                    .as_object()
                                    .map(|o| o.keys().cloned().collect::<Vec<_>>().join(","))
                                    .unwrap_or_default()
                            ));
                        }
                    }
                    if ty.contains("turn/") && samples.len() < 2 {
                        samples.push(format!(
                            "[{ty}] {}",
                            trimmed.chars().take(300).collect::<String>()
                        ));
                    }
                }
            }
            Err(e) => errors.push(format!("{}: {e}", path.display())),
        }
    }

    let mut lines = vec![
        format!("扫描文件: {} / {}", limit.min(files.len()), files.len()),
        format!("事件行数: {total_lines}，解析成功 {events}"),
        String::new(),
        "事件类型分布:".to_string(),
    ];
    let mut types: Vec<_> = by_type.iter().collect();
    types.sort_by(|a, b| b.1.cmp(a.1));
    for (k, v) in types.iter().take(24) {
        lines.push(format!("  {k}: {v}"));
    }
    if !errors.is_empty() {
        lines.push(String::new());
        lines.push("错误:".into());
        for e in errors.iter().take(5) {
            lines.push(format!("  {e}"));
        }
    }
    lines.push(String::new());
    lines.push("assistant/message 的 usage 采样:".into());
    for s in &usage_samples {
        lines.push(format!("  {s}"));
    }
    lines.push(String::new());
    lines.push("turn 事件样本:".into());
    for s in &samples {
        lines.push(format!("  {s}"));
    }

    ActionResult {
        ok: true,
        action: "scan".into(),
        message: lines.join("\n"),
        output: String::new(),
    }
}

/// One row of the per-model breakdown table.
#[derive(Serialize, Clone)]
struct ModelRow {
    model: String,
    calls: u64,
    input_tokens: u64,
    output_tokens: u64,
    cache_read_tokens: u64,
    cache_write_tokens: u64,
    reasoning_tokens: u64,
    peak_cost: f64,
    offpeak_cost: f64,
    cost: f64,
    cache_hit_pct: f64,
    /// Share of the range total, so the UI can draw an inline bar.
    cost_share: f64,
}

#[derive(Serialize, Clone)]
struct SessionRow {
    session: String,
    calls: u64,
    tokens: u64,
    cost: f64,
}

#[derive(Serialize, Clone)]
struct UsageAnalysis {
    ok: bool,
    /// 0 means "everything we have".
    range_days: u32,
    range_label: String,
    total: Bucket,
    cache_hit_pct: f64,
    today_cost: f64,
    month_cost: f64,
    month_elapsed_days: u32,
    month_total_days: u32,
    /// Linear extrapolation of the current month, for the "預計" figure.
    month_projection: f64,
    models: Vec<ModelRow>,
    sessions: Vec<SessionRow>,
    first_date: String,
    last_date: String,
    error: Option<String>,
}

/// Everything the analysis page needs, in one call: totals, per-model rows and
/// the top sessions for a time range.
#[tauri::command]
fn usage_analysis(app: AppHandle, days: Option<u32>) -> UsageAnalysis {
    let range_days = days.unwrap_or(0);
    let fail = |err: String| UsageAnalysis {
        ok: false,
        range_days,
        range_label: String::new(),
        total: Bucket::default(),
        cache_hit_pct: 0.0,
        today_cost: 0.0,
        month_cost: 0.0,
        month_elapsed_days: 0,
        month_total_days: 0,
        month_projection: 0.0,
        models: Vec::new(),
        sessions: Vec::new(),
        first_date: String::new(),
        last_date: String::new(),
        error: Some(err),
    };

    let all = match load_all_days(&app) {
        Ok(d) => d,
        Err(e) => return fail(e),
    };
    if all.is_empty() {
        return fail("还没有本地用量数据。在设置里点「导入插件历史用量」，或让 harness 跑一段时间。".into());
    }

    let today = chrono::Local::now().date_naive();
    let month_prefix = today.format("%Y-%m").to_string();

    // Range filter: keep the last N local calendar days, counting today.
    let cutoff = if range_days == 0 {
        None
    } else {
        Some((today - chrono::Duration::days(range_days.saturating_sub(1) as i64)).format("%Y-%m-%d").to_string())
    };

    let mut total = Bucket::default();
    let mut models: HashMap<String, Bucket> = HashMap::new();
    let mut sessions: HashMap<String, Bucket> = HashMap::new();
    let mut today_cost = 0.0;
    let mut month_cost = 0.0;
    let today_key = today.format("%Y-%m-%d").to_string();

    for day in &all {
        if let Some(ref c) = cutoff {
            if day.date.as_str() < c.as_str() {
                continue;
            }
        }
        total.merge(&day.total);
        if day.date == today_key {
            today_cost += day.total.cost;
        }
        if day.date.starts_with(&month_prefix) {
            month_cost += day.total.cost;
        }
        for (model, bucket) in &day.by_model {
            models.entry(model.clone()).or_default().merge(bucket);
        }
        for (session, bucket) in &day.by_session {
            sessions.entry(session.clone()).or_default().merge(bucket);
        }
    }

    let total_cost = total.cost;
    let mut model_rows: Vec<ModelRow> = models
        .into_iter()
        .map(|(model, b)| ModelRow {
            model,
            calls: b.calls,
            input_tokens: b.input_tokens,
            output_tokens: b.output_tokens,
            cache_read_tokens: b.cache_read_tokens,
            cache_write_tokens: b.cache_write_tokens,
            reasoning_tokens: b.reasoning_tokens,
            peak_cost: b.peak_cost,
            offpeak_cost: b.offpeak_cost,
            cost: b.cost,
            cache_hit_pct: b.cache_hit_pct(),
            cost_share: if total_cost > 0.0 {
                b.cost / total_cost * 100.0
            } else {
                0.0
            },
        })
        .collect();
    model_rows.sort_by(|a, b| b.cost.partial_cmp(&a.cost).unwrap_or(std::cmp::Ordering::Equal));

    let mut session_rows: Vec<SessionRow> = sessions
        .into_iter()
        .map(|(session, b)| SessionRow {
            session,
            calls: b.calls,
            tokens: b.tokens(),
            cost: b.cost,
        })
        .collect();
    session_rows.sort_by(|a, b| b.cost.partial_cmp(&a.cost).unwrap_or(std::cmp::Ordering::Equal));
    session_rows.truncate(10);

    // Month projection: elapsed days include today.
    let elapsed = today.day();
    let total_days_in_month = days_in_month(today.year(), today.month());
    let projection = if elapsed > 0 {
        month_cost / elapsed as f64 * total_days_in_month as f64
    } else {
        0.0
    };

    let first_date = all.first().map(|d| d.date.clone()).unwrap_or_default();
    let last_date = all.last().map(|d| d.date.clone()).unwrap_or_default();
    let range_label = if range_days == 0 {
        format!("全部（{first_date} 起）")
    } else {
        format!("近 {range_days} 天")
    };

    UsageAnalysis {
        ok: true,
        range_days,
        range_label,
        cache_hit_pct: total.cache_hit_pct(),
        total,
        today_cost,
        month_cost,
        month_elapsed_days: elapsed,
        month_total_days: total_days_in_month,
        month_projection: projection,
        models: model_rows,
        sessions: session_rows,
        first_date,
        last_date,
        error: None,
    }
}

/// Days in a calendar month (handles leap years without a date library call).
fn days_in_month(year: i32, month: u32) -> u32 {
    match month {
        1 | 3 | 5 | 7 | 8 | 10 | 12 => 31,
        4 | 6 | 9 | 11 => 30,
        2 => {
            if (year % 4 == 0 && year % 100 != 0) || year % 400 == 0 {
                29
            } else {
                28
            }
        }
        _ => 30,
    }
}

/// Build the per-day usage map straight from the session logs.
///
/// Every billed model call lands as one `assistant/message` event carrying
/// `data.usage` (the five token buckets) and `data.message.source`
/// (provider/model). `time` is the event's own millisecond timestamp, so days
/// are bucketed in local time exactly like the plugin did.
///
/// Returns (day map, files scanned, usage events seen).
fn collect_session_usage(
    cutoff_ms: i64,
) -> Result<(HashMap<String, DayUsage>, usize, usize), String> {
    let root = sessions_root().ok_or("找不到 ~/.dsh/sessions")?;
    let files = session_files(&root);

    let mut days: HashMap<String, DayUsage> = HashMap::new();
    let mut scanned = 0usize;
    let mut usage_events = 0usize;

    for path in files {
        // Skip whole files that predate the window: a session file only grows,
        // so its mtime bounds the newest event inside it.
        if cutoff_ms > 0 {
            let Ok(meta) = std::fs::metadata(&path) else {
                continue;
            };
            let Ok(modified) = meta.modified() else {
                continue;
            };
            let mtime_ms = modified
                .duration_since(UNIX_EPOCH)
                .map(|d| d.as_millis() as i64)
                .unwrap_or(0);
            if mtime_ms < cutoff_ms {
                continue;
            }
        }

        let Ok(lines) = read_session_lines(&path) else {
            continue;
        };
        scanned += 1;

        for line in lines {
            let trimmed = line.trim();
            // Cheap pre-filter before paying for a full JSON parse.
            if trimmed.is_empty() || !trimmed.contains("assistant/message") {
                continue;
            }
            let Ok(v) = serde_json::from_str::<serde_json::Value>(trimmed) else {
                continue;
            };
            if v["type"].as_str() != Some("assistant/message") {
                continue;
            }
            let usage = &v["data"]["usage"];
            if usage.is_null() {
                continue;
            }
            let ts = v["time"].as_i64().unwrap_or(0);
            if ts <= 0 {
                continue;
            }
            if cutoff_ms > 0 && ts < cutoff_ms {
                continue;
            }

            let input = usage["inputTokens"].as_u64().unwrap_or(0);
            let output = usage["outputTokens"].as_u64().unwrap_or(0);
            let cache_read = usage["cacheReadTokens"].as_u64().unwrap_or(0);
            let cache_write = usage["cacheWriteTokens"].as_u64().unwrap_or(0);
            let reasoning = usage["reasoningTokens"].as_u64().unwrap_or(0);
            let model = v["data"]["message"]["source"]["model"]
                .as_str()
                .unwrap_or("unknown")
                .to_string();
            let session = v["data"]["message"]["id"]
                .as_str()
                .map(|_| path.file_stem().and_then(|s| s.to_str()).unwrap_or("").to_string())
                .unwrap_or_default();

            usage_events += 1;

            // Session logs carry no cost figure (pricing is a plugin concern),
            // so cost stays 0 here and the day file keeps whatever the plugin
            // import already recorded. Peak/off-peak cannot be derived either.
            let date = local_date(ts);
            let day = days.entry(date.clone()).or_insert_with(|| DayUsage {
                date,
                ..Default::default()
            });
            day.total
                .add(input, output, cache_read, cache_write, reasoning, 0.0, false);
            day.by_model.entry(model).or_default().add(
                input, output, cache_read, cache_write, reasoning, 0.0, false,
            );
            if !session.is_empty() {
                day.by_session.entry(session).or_default().add(
                    input, output, cache_read, cache_write, reasoning, 0.0, false,
                );
            }
        }
    }

    Ok((days, scanned, usage_events))
}

/// Resolve the usage directory without an AppHandle (CLI paths).
fn usage_dir_headless() -> Result<PathBuf, String> {
    let appdata = std::env::var("APPDATA").map_err(|e| format!("取不到 APPDATA: {e}"))?;
    let dir = PathBuf::from(appdata)
        .join("com.dshpanel.app")
        .join("usage");
    std::fs::create_dir_all(&dir).map_err(|e| format!("创建用量目录失败: {e}"))?;
    Ok(dir)
}

/// Core of the session refresh, independent of Tauri so the CLI can run it.
fn scan_sessions_at(dir: &PathBuf, days: Option<u32>) -> ActionResult {
    let cutoff_ms = match days {
        Some(n) if n > 0 => {
            let now = chrono::Local::now().date_naive();
            let start = now - chrono::Duration::days(n.saturating_sub(1) as i64);
            start
                .and_hms_opt(0, 0, 0)
                .and_then(|dt| dt.and_local_timezone(chrono::Local).single())
                .map(|dt| dt.timestamp_millis())
                .unwrap_or(0)
        }
        _ => 0,
    };

    let (found, scanned, events) = match collect_session_usage(cutoff_ms) {
        Ok(v) => v,
        Err(e) => {
            return ActionResult {
                ok: false,
                action: "scan".into(),
                message: e,
                output: String::new(),
            }
        }
    };

    let mut written = 0usize;
    let mut tokens = 0u64;
    for (date, scanned_day) in &found {
        // Keep the existing cost / peak split (the scan cannot produce them).
        let existing = load_day(&dir.join(format!("{date}.json")), date);
        let mut merged = scanned_day.clone();
        merged.total.cost = existing.total.cost.max(merged.total.cost);
        merged.total.peak_cost = existing.total.peak_cost;
        merged.total.offpeak_cost = existing.total.offpeak_cost;
        merged.total.peak_calls = existing.total.peak_calls;
        for (model, bucket) in merged.by_model.iter_mut() {
            if let Some(old) = existing.by_model.get(model) {
                bucket.cost = old.cost.max(bucket.cost);
                bucket.peak_cost = old.peak_cost;
                bucket.offpeak_cost = old.offpeak_cost;
                bucket.peak_calls = old.peak_calls;
            }
        }
        tokens += merged.total.tokens();
        if save_day(dir, &merged).is_ok() {
            written += 1;
        }
    }

    ActionResult {
        ok: true,
        action: "scan".into(),
        message: format!(
            "已扫描 {scanned} 个会话文件、{events} 条用量事件，更新 {written} 天（{tokens} token）。\
             会话日志不含价格，花费沿用已导入的数据。"
        ),
        output: String::new(),
    }
}

/// Refresh the local store from the session logs (works with no plugin installed).
///
/// Merge rule: a day the scanner found data for is *replaced*; days the scanner
/// did not cover keep whatever is already on disk. That keeps the plugin-imported
/// history (which carries cost) from being wiped by a scan that cannot see it.
#[tauri::command]
fn scan_sessions(app: AppHandle, days: Option<u32>) -> ActionResult {
    match usage_dir(&app) {
        Ok(dir) => scan_sessions_at(&dir, days),
        Err(e) => ActionResult {
            ok: false,
            action: "scan".into(),
            message: e,
            output: String::new(),
        },
    }
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    // Headless diagnostics: `dsh-panel.exe --scan-sessions [file-limit]`.
    // Handled BEFORE the job-detach step, because detaching exits the process to
    // relaunch through explorer - which would swallow the diagnostic entirely.
    // Output goes to a file, not stdout: the Windows GUI subsystem gives this
    // binary no console, so `println!` would vanish.
    let argv: Vec<String> = std::env::args().collect();
    if let Some(pos) = argv.iter().position(|a| a == "--scan-sessions") {
        let limit = argv.get(pos + 1).and_then(|s| s.parse::<usize>().ok());
        let result = scan_sessions_diag(limit);
        let out = std::env::temp_dir().join("dsh-panel-scan.txt");
        let _ = std::fs::write(&out, &result.message);
        std::process::exit(0);
    }

    // `dsh-panel.exe --scan-sessions-apply [days]` runs the real refresh.
    if let Some(pos) = argv.iter().position(|a| a == "--scan-sessions-apply") {
        let days = argv.get(pos + 1).and_then(|s| s.parse::<u32>().ok());
        let message = match usage_dir_headless() {
            Ok(dir) => scan_sessions_at(&dir, days).message,
            Err(e) => e,
        };
        let out = std::env::temp_dir().join("dsh-panel-scan-apply.txt");
        let _ = std::fs::write(&out, message);
        std::process::exit(0);
    }

    detach_from_job_if_needed();
    tauri::Builder::default()
        .plugin(tauri_plugin_dialog::init())
        .setup(|app| {
            let open_panel = MenuItem::with_id(app, "open_panel", "打开面板", true, None::<&str>)?;
            let launch = MenuItem::with_id(app, "launch", "打开 Harness", true, None::<&str>)?;
            let check = MenuItem::with_id(app, "check", "立即检查更新", true, None::<&str>)?;
            let quit = MenuItem::with_id(app, "quit", "退出", true, None::<&str>)?;
            let menu = Menu::with_items(app, &[&open_panel, &launch, &check, &quit])?;

            TrayIconBuilder::with_id(TRAY_ID)
                .icon(tray_image(false, taskbar_is_light()))
                .tooltip("DSH Panel")
                .menu(&menu)
                .show_menu_on_left_click(false)
                .on_menu_event(|app, event| match event.id().as_ref() {
                    "quit" => app.exit(0),
                    "open_panel" => show_panel(app),
                    "launch" => {
                        tauri::async_runtime::spawn(async move {
                            let _ = open_harness_inner(DEFAULT_HARNESS_PORT).await;
                        });
                    }
                    "check" => {
                        let app = app.clone();
                        tauri::async_runtime::spawn(async move {
                            let info = run_check(&app).await;
                            let _ = app.emit("update-checked", &info);
                        });
                    }
                    _ => {}
                })
                .on_tray_icon_event(|tray, event| {
                    if let TrayIconEvent::Click {
                        button: MouseButton::Left,
                        button_state: MouseButtonState::Up,
                        ..
                    } = event
                    {
                        show_panel(tray.app_handle());
                    }
                })
                .build(app)?;

            // Background sweep: checks on startup, then at most once every 24h.
            let handle = app.handle().clone();
            std::thread::spawn(move || loop {
                if check_due(&handle) {
                    let info = tauri::async_runtime::block_on(run_check(&handle));
                    let _ = handle.emit("update-checked", &info);
                }
                std::thread::sleep(Duration::from_secs(3600));
            });

            // Poll the harness port so the tray icon reflects whether it is really
            // up. Repaints only when the state flips, plus once at startup.
            let handle = app.handle().clone();
            std::thread::spawn(move || {
                let url = format!("http://127.0.0.1:{}/", DEFAULT_HARNESS_PORT);
                let mut first = true;
                loop {
                    let alive = tauri::async_runtime::block_on(port_alive(&url));
                    let light = taskbar_is_light();
                    // Both swaps must run, so use non-short-circuiting `|`.
                    let changed = (HARNESS_RUNNING.swap(alive, Ordering::Relaxed) != alive)
                        | (TASKBAR_LIGHT.swap(light, Ordering::Relaxed) != light);
                    if changed || first {
                        first = false;
                        refresh_tray(&handle);
                        let _ = handle.emit("harness-state", alive);
                    }
                    std::thread::sleep(Duration::from_secs(HARNESS_POLL_SECS));
                }
            });

            Ok(())
        })
        // Tray-resident: closing the window hides it instead of quitting.
        .on_window_event(|window, event| {
            if let tauri::WindowEvent::CloseRequested { api, .. } = event {
                api.prevent_close();
                let _ = window.hide();
            }
        })
        .invoke_handler(tauri::generate_handler![
            get_local_info,
            check_update,
            upgrade_dsh,
            open_harness,
            start_harness_inline,
            stop_harness,
            get_settings,
            set_desktop_source_dir,
            start_desktop_app,
            stop_desktop_app,
            desktop_running,
            get_balance_native,
            usage_series,
            usage_analysis,
            scan_sessions,
            scan_sessions_diag,
            list_plugins,
            install_plugin,
            remove_plugin,
            upgrade_plugins,
            plugin_op_running,
            feishu_bridge_status,
            feishu_bridge_start,
            feishu_bridge_stop,
            open_harness_page,
            hermes_status,
            open_hermes_page,
            harness_running,
            quit_app
        ])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
